//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarSecurity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfRASolarERPPages
    {
        public ListOfRASolarERPPages()
        {
            this.UserRoleOrGroupWisePermission = new HashSet<UserRoleOrGroupWisePermission>();
        }
    
        public string ModuleID { get; set; }
        public string PageID { get; set; }
        public string PageNameToLink { get; set; }
        public string PageName { get; set; }
        public string ModuleName { get; set; }
        public byte Status { get; set; }
        public string MessageToShow { get; set; }
    
        public virtual ICollection<UserRoleOrGroupWisePermission> UserRoleOrGroupWisePermission { get; set; }
    }
}
