//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarSecurity.Model
{
    using System;
    
    public partial class ListOfPagesWithAccessRightsForThisUser
    {
        public string PageID { get; set; }
        public string PageName { get; set; }
        public string ModuleID { get; set; }
        public string IsAccessibleForThisUser { get; set; }
        public string MessageToShow { get; set; }
    }
}
