//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarSecurity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationInformation
    {
        public LocationInformation()
        {
            this.UserLocationMapping = new HashSet<UserLocationMapping>();
        }
    
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public Nullable<byte> LocationType { get; set; }
        public string ParentLocation { get; set; }
        public byte Status { get; set; }
        public string UserID { get; set; }
        public System.DateTime EntryTime { get; set; }
    
        public virtual Sys_StatusInfo Sys_StatusInfo { get; set; }
        public virtual ICollection<UserLocationMapping> UserLocationMapping { get; set; }
    }
}
