//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarSecurity.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class RASolarERP_SecurityAdminEntities : DbContext
    {
        public RASolarERP_SecurityAdminEntities()
            : base("name=RASolarERP_SecurityAdminEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ListOfRASolarERPPages> ListOfRASolarERPPages { get; set; }
        public DbSet<LocationInformation> LocationInformation { get; set; }
        public DbSet<Sys_StatusInfo> Sys_StatusInfo { get; set; }
        public DbSet<UserInformation> UserInformation { get; set; }
        public DbSet<UserLocationMapping> UserLocationMapping { get; set; }
        public DbSet<UserRoleOrGroupInformation> UserRoleOrGroupInformation { get; set; }
        public DbSet<UserRoleOrGroupWisePermission> UserRoleOrGroupWisePermission { get; set; }
    
        public virtual ObjectResult<ListOfPagesWithAccessRightsForThisUser> ListOfPagesWithAccessRightsForThisUser(string prmUserID, string prmPageOption, string prmPageID)
        {
            var prmUserIDParameter = prmUserID != null ?
                new ObjectParameter("prmUserID", prmUserID) :
                new ObjectParameter("prmUserID", typeof(string));
    
            var prmPageOptionParameter = prmPageOption != null ?
                new ObjectParameter("prmPageOption", prmPageOption) :
                new ObjectParameter("prmPageOption", typeof(string));
    
            var prmPageIDParameter = prmPageID != null ?
                new ObjectParameter("prmPageID", prmPageID) :
                new ObjectParameter("prmPageID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListOfPagesWithAccessRightsForThisUser>("ListOfPagesWithAccessRightsForThisUser", prmUserIDParameter, prmPageOptionParameter, prmPageIDParameter);
        }
    }
}
