//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarSecurity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_StatusInfo
    {
        public Sys_StatusInfo()
        {
            this.LocationInformation = new HashSet<LocationInformation>();
            this.UserInformation = new HashSet<UserInformation>();
            this.UserRoleOrGroupInformation = new HashSet<UserRoleOrGroupInformation>();
        }
    
        public byte StatusID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<LocationInformation> LocationInformation { get; set; }
        public virtual ICollection<UserInformation> UserInformation { get; set; }
        public virtual ICollection<UserRoleOrGroupInformation> UserRoleOrGroupInformation { get; set; }
    }
}
