//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarSecurity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleOrGroupWisePermission
    {
        public string RoleOrGroupID { get; set; }
        public string ModuleID { get; set; }
        public string PageID { get; set; }
        public Nullable<bool> IsGrantedForSelect { get; set; }
        public Nullable<bool> IsGrantedForInsert { get; set; }
        public Nullable<bool> IsGrantedForUpdate { get; set; }
        public Nullable<bool> IsGrantedForDelete { get; set; }
        public byte Status { get; set; }
        public System.DateTime EntryTime { get; set; }
    
        public virtual ListOfRASolarERPPages ListOfRASolarERPPages { get; set; }
        public virtual UserRoleOrGroupInformation UserRoleOrGroupInformation { get; set; }
    }
}
