//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_SpecialAccount
    {
        public byte SAIID { get; set; }
        public string AccountNo { get; set; }
    
        public virtual Acc_ChartOfAccounts Acc_ChartOfAccounts { get; set; }
    }
}
