//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_FinalTransDetail
    {
        public string LocationCode { get; set; }
        public System.DateTime TransDate { get; set; }
        public string ProjectCode { get; set; }
        public string TransNo { get; set; }
        public int SerialNo { get; set; }
        public string AccountNo { get; set; }
        public string Particulars { get; set; }
        public decimal Amount { get; set; }
        public string RefEntrySource { get; set; }
    
        public virtual Acc_ChartOfAccounts Acc_ChartOfAccounts { get; set; }
        public virtual Acc_FinalTransMaster Acc_FinalTransMaster { get; set; }
    }
}
