//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_TransNoCount
    {
        public string LocationCode { get; set; }
        public System.DateTime TransDate { get; set; }
        public string TransNo { get; set; }
        public Nullable<int> TransCount { get; set; }
        public int EntrySerial { get; set; }
    }
}
