//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_FinalTransMaster
    {
        public Acc_FinalTransMaster()
        {
            this.Acc_FinalTransDetail = new HashSet<Acc_FinalTransDetail>();
        }
    
        public string LocationCode { get; set; }
        public System.DateTime TransDate { get; set; }
        public string ProjectCode { get; set; }
        public string TransNo { get; set; }
        public string GenParticulars { get; set; }
        public bool CBVoucher { get; set; }
        public string CBVType { get; set; }
        public bool IsAutoEntry { get; set; }
        public string EntrySource { get; set; }
        public string EntryIdentFlag { get; set; }
        public string ReversalTransNo { get; set; }
        public string ReversalOrOriginalFlag { get; set; }
        public string RefDocType { get; set; }
        public string RefDocNo { get; set; }
        public string RefMRRSeqNo { get; set; }
        public string RefChallanSeqNo { get; set; }
        public string RefSPSSeqNo { get; set; }
        public string RefCustomerCode { get; set; }
        public string RefVendorID { get; set; }
        public string RefEmployeeID { get; set; }
        public string SenderOrReceiverFlag { get; set; }
        public string SenderOrReceiverLocationCode { get; set; }
        public string SenderOrReceiverTransNo { get; set; }
        public int RefEntryNo { get; set; }
        public string UserID { get; set; }
        public System.DateTime EntryTime { get; set; }
    
        public virtual ICollection<Acc_FinalTransDetail> Acc_FinalTransDetail { get; set; }
        public virtual Common_ProjectInfo Common_ProjectInfo { get; set; }
    }
}
