//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    
    public partial class AccountingDataEntryStatus
    {
        public string Zone_Name { get; set; }
        public string Region_Name { get; set; }
        public string Unit_Code { get; set; }
        public string Unit_Name { get; set; }
        public Nullable<decimal> Cash_OpeningBalance { get; set; }
        public Nullable<decimal> Cash_Received { get; set; }
        public Nullable<decimal> Cash_PaymentOrBankDeposit { get; set; }
        public Nullable<decimal> Cash_ClosingBalance { get; set; }
        public Nullable<decimal> Bank_OpeningBalance { get; set; }
        public Nullable<decimal> Bank_Deposit { get; set; }
        public Nullable<decimal> Bank_TT_DD_Others { get; set; }
        public Nullable<decimal> Bank_ClosingBalance { get; set; }
        public Nullable<decimal> CollectionReconciliationBalance { get; set; }
        public Nullable<int> NoOfSales_SHS { get; set; }
        public Nullable<decimal> InventoryClosingBalance { get; set; }
        public Nullable<System.DateTime> FinalizedByRM { get; set; }
        public Nullable<System.DateTime> FinalizedByZM { get; set; }
        public Nullable<System.DateTime> FinalizedByHO { get; set; }
    }
}
