//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    
    public partial class AccShowAccountWiseBreakdown
    {
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
