//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aud_AuditAdjustmentRelatedAccountingTransaction
    {
        public string LocationCode { get; set; }
        public System.DateTime TransDate { get; set; }
        public string ProjectCode { get; set; }
        public string TransNo { get; set; }
        public string AuditSeqNo { get; set; }
        public string ReasonCode { get; set; }
        public Nullable<System.DateTime> RefVoucherDate { get; set; }
        public string ResponsibleEmployeeID { get; set; }
        public string Remarks { get; set; }
    }
}
