//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_LocationWiseBankAccountInfo
    {
        public string LocationCode { get; set; }
        public string BankID { get; set; }
        public string BankBranchID { get; set; }
        public string BankAccountNumber { get; set; }
        public string BranchName { get; set; }
        public string BankAccountType { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> AccountOpeningDate { get; set; }
        public string GLAccountNo { get; set; }
        public string Signatory1 { get; set; }
        public string Signatory2 { get; set; }
        public string Remarks { get; set; }
        public byte Status { get; set; }
    
        public virtual Acc_ChartOfAccounts Acc_ChartOfAccounts { get; set; }
        public virtual Common_BankInfo Common_BankInfo { get; set; }
        public virtual Common_BankAccountType Common_BankAccountType { get; set; }
        public virtual Common_BankBranchInfo Common_BankBranchInfo { get; set; }
    }
}
