//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_BankBranchInfo
    {
        public Common_BankBranchInfo()
        {
            this.Common_LocationWiseBankAccountInfo = new HashSet<Common_LocationWiseBankAccountInfo>();
        }
    
        public string BankID { get; set; }
        public string BankBranchID { get; set; }
        public string BankBranchName { get; set; }
        public string BankBranchNameInBangla { get; set; }
        public string LetterAddressTo { get; set; }
        public string LetterAddressToInBangla { get; set; }
        public string BankAddress1 { get; set; }
        public string BankAddress1InBangla { get; set; }
        public string BankAddress2 { get; set; }
        public string BankAddress2InBangla { get; set; }
        public byte Status { get; set; }
        public Nullable<bool> IsItAOnlineBranch { get; set; }
    
        public virtual Common_BankInfo Common_BankInfo { get; set; }
        public virtual ICollection<Common_LocationWiseBankAccountInfo> Common_LocationWiseBankAccountInfo { get; set; }
    }
}
