//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_BankAccountType
    {
        public Common_BankAccountType()
        {
            this.Common_LocationWiseBankAccountInfo = new HashSet<Common_LocationWiseBankAccountInfo>();
        }
    
        public string BankAccountTypeID { get; set; }
        public string BATypeDescription { get; set; }
        public string BATypeDescriptionInBangla { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Common_LocationWiseBankAccountInfo> Common_LocationWiseBankAccountInfo { get; set; }
    }
}
