//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_BankInfo
    {
        public Common_BankInfo()
        {
            this.Common_LocationWiseBankAccountInfo = new HashSet<Common_LocationWiseBankAccountInfo>();
            this.Common_BankBranchInfo = new HashSet<Common_BankBranchInfo>();
        }
    
        public string BankID { get; set; }
        public string BankName { get; set; }
        public byte Status { get; set; }
        public Nullable<bool> IsItAOnlineBank { get; set; }
    
        public virtual ICollection<Common_LocationWiseBankAccountInfo> Common_LocationWiseBankAccountInfo { get; set; }
        public virtual ICollection<Common_BankBranchInfo> Common_BankBranchInfo { get; set; }
    }
}
