//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_SalaryPayRegisterByMonthNEmployee
    {
        public string YearMonth { get; set; }
        public string EmployeeID { get; set; }
        public string SalaryLocationCode { get; set; }
        public string EmployeeLocationCode { get; set; }
        public string ModeOfSalaryPayment { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> TotalAdditionAmount { get; set; }
        public Nullable<decimal> TotalDeductionAmount { get; set; }
        public Nullable<decimal> TotalTakeHomeAmount { get; set; }
        public Nullable<decimal> PayableSalaryOtherThanTADAAmount { get; set; }
        public Nullable<decimal> PayableTADAAmount { get; set; }
        public Nullable<decimal> PayableBonusAmount { get; set; }
        public Nullable<decimal> PayableTotalSalaryAmount { get; set; }
        public Nullable<decimal> PaidSalaryOtherThanTADAAmount { get; set; }
        public Nullable<decimal> PaidTADAAmount { get; set; }
        public Nullable<decimal> PaidBonusAmount { get; set; }
        public Nullable<decimal> PaidTotalSalaryAmount { get; set; }
        public string PaidInYearMonth { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string RefAELocationCode { get; set; }
        public Nullable<System.DateTime> RefAETransDate { get; set; }
        public string RefAEProjectCode { get; set; }
        public string RefAETransNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public byte Status { get; set; }
        public string Remarks { get; set; }
    }
}
