//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    
    public partial class MonthlyAccountingSummaryStatement
    {
        public int SalesQuantitySHS { get; set; }
        public decimal SalesAmountSHS { get; set; }
        public int SalesQuantityBioGAS { get; set; }
        public decimal SalesAmountBioGAS { get; set; }
        public decimal CashInHandOpeningBalance { get; set; }
        public Nullable<decimal> CollectionDPSHS { get; set; }
        public Nullable<decimal> CollectionPrincipalSHS { get; set; }
        public Nullable<decimal> CollectionServiceChrgeSHS { get; set; }
        public Nullable<decimal> CollectionAsAdvanceSHS { get; set; }
        public decimal CollectionSparePartsSHS { get; set; }
        public Nullable<decimal> CollectionReconSHS { get; set; }
        public Nullable<decimal> CollectionTotalSHS { get; set; }
        public decimal CollectionDPBioGAS { get; set; }
        public decimal CollectionPrincipalBioGAS { get; set; }
        public decimal CollectionServiceChrgeBioGAS { get; set; }
        public decimal CollectionAsAdvanceBioGAS { get; set; }
        public decimal CollectionSparePartsBioGAS { get; set; }
        public decimal CollectionReconBioGAS { get; set; }
        public Nullable<decimal> CollectionTotalBioGAS { get; set; }
        public decimal NoticePaySalary { get; set; }
        public decimal AuditClaimReceivable { get; set; }
        public decimal OthersIncome { get; set; }
        public Nullable<decimal> TotalCashInflowInThisPeriod { get; set; }
        public decimal BankDeposit { get; set; }
        public decimal OnlineTransfer { get; set; }
        public decimal InterUnitTransfer { get; set; }
        public decimal MonthlyExpensesSHS { get; set; }
        public decimal MonthlyExpensesBioGAS { get; set; }
        public Nullable<decimal> TotalCashOutflowSHS { get; set; }
        public decimal TotalCashOutflowBioGAS { get; set; }
        public Nullable<decimal> TotalCashOutflowInThisPeriod { get; set; }
        public decimal CashInHandClosingBalance { get; set; }
        public Nullable<decimal> CashInHandClosingBalanceCalculative { get; set; }
        public Nullable<decimal> DifferenceInActualVsCalculativeCashInHand { get; set; }
        public decimal CashAtBankOpeningBalance { get; set; }
        public decimal CashDeposit { get; set; }
        public decimal TTnDD { get; set; }
        public decimal SalaryPayable { get; set; }
        public decimal BankCharge { get; set; }
        public decimal CashAtBankClosingBalance { get; set; }
    }
}
