//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarAMS.Model
{
    using System;
    
    public partial class TrialBalance
    {
        public string AccNo { get; set; }
        public string AccName { get; set; }
        public byte AccLevel { get; set; }
        public int Leaf { get; set; }
        public string ParentNo { get; set; }
        public string SortCol { get; set; }
        public decimal OpeningB { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public Nullable<decimal> ClosingB { get; set; }
        public string ParCapSub { get; set; }
    }
}
