//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aud_AuditingMaster
    {
        public Aud_AuditingMaster()
        {
            this.Aud_AuditingDetailsForAuditors = new HashSet<Aud_AuditingDetailsForAuditors>();
            this.Aud_AuditingMaster1 = new HashSet<Aud_AuditingMaster>();
        }
    
        public string LocationCode { get; set; }
        public string AuditSeqNo { get; set; }
        public System.DateTime AuditStartDate { get; set; }
        public Nullable<System.DateTime> AuditFinishDate { get; set; }
        public System.DateTime AuditPeriodFromDate { get; set; }
        public System.DateTime AuditPeriodToDate { get; set; }
        public string RefLastAuditSeqNo { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Aud_AuditingDetailsForAuditors> Aud_AuditingDetailsForAuditors { get; set; }
        public virtual ICollection<Aud_AuditingMaster> Aud_AuditingMaster1 { get; set; }
        public virtual Aud_AuditingMaster Aud_AuditingMaster2 { get; set; }
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
    }
}
