//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aud_AuditingDetailsForAuditors
    {
        public string LocationCode { get; set; }
        public string AuditSeqNo { get; set; }
        public string AuditorsEmployeeID { get; set; }
    
        public virtual Aud_AuditingMaster Aud_AuditingMaster { get; set; }
    }
}
