//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_DistrictInfo
    {
        public Common_DistrictInfo()
        {
            this.Hrm_EmployeeInfo = new HashSet<Hrm_EmployeeInfo>();
            this.Hrm_EmployeeInfo1 = new HashSet<Hrm_EmployeeInfo>();
            this.Hrm_EmployeeInfo2 = new HashSet<Hrm_EmployeeInfo>();
            this.Common_UpazillaInfo = new HashSet<Common_UpazillaInfo>();
        }
    
        public string DIST_CODE { get; set; }
        public string DIST_NAME { get; set; }
        public System.DateTime CREATED { get; set; }
        public System.DateTime MODIFIED { get; set; }
    
        public virtual ICollection<Hrm_EmployeeInfo> Hrm_EmployeeInfo { get; set; }
        public virtual ICollection<Hrm_EmployeeInfo> Hrm_EmployeeInfo1 { get; set; }
        public virtual ICollection<Hrm_EmployeeInfo> Hrm_EmployeeInfo2 { get; set; }
        public virtual ICollection<Common_UpazillaInfo> Common_UpazillaInfo { get; set; }
    }
}
