//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_LocationInfo
    {
        public Common_LocationInfo()
        {
            this.Aud_AuditingMaster = new HashSet<Aud_AuditingMaster>();
            this.Hrm_EmployeeInfo = new HashSet<Hrm_EmployeeInfo>();
            this.Hrm_EmployeeTransfer = new HashSet<Hrm_EmployeeTransfer>();
            this.Hrm_EmployeeTransfer1 = new HashSet<Hrm_EmployeeTransfer>();
            this.Hrm_EmployeeTransfer2 = new HashSet<Hrm_EmployeeTransfer>();
            this.Hrm_LocationWiseEmployee = new HashSet<Hrm_LocationWiseEmployee>();
        }
    
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public byte LocationType { get; set; }
        public string ParentLocation { get; set; }
        public byte Status { get; set; }
        public Nullable<bool> TempIsInventoryStockUpdateFinish { get; set; }
        public Nullable<byte> BackDayAllowedForTransaction { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public string NewLocationCode { get; set; }
        public Nullable<decimal> IDCOL_BranchID { get; set; }
        public string IDCOL_BranchName { get; set; }
        public string ManagersMobileNo { get; set; }
        public Nullable<bool> IsItPoorCollectionEfficiencyUnit { get; set; }
        public string ManagersEmployeeID { get; set; }
    
        public virtual ICollection<Aud_AuditingMaster> Aud_AuditingMaster { get; set; }
        public virtual ICollection<Hrm_EmployeeInfo> Hrm_EmployeeInfo { get; set; }
        public virtual ICollection<Hrm_EmployeeTransfer> Hrm_EmployeeTransfer { get; set; }
        public virtual ICollection<Hrm_EmployeeTransfer> Hrm_EmployeeTransfer1 { get; set; }
        public virtual ICollection<Hrm_EmployeeTransfer> Hrm_EmployeeTransfer2 { get; set; }
        public virtual ICollection<Hrm_LocationWiseEmployee> Hrm_LocationWiseEmployee { get; set; }
    }
}
