//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_UpazillaInfo
    {
        public Common_UpazillaInfo()
        {
            this.Hrm_EmployeeInfo = new HashSet<Hrm_EmployeeInfo>();
            this.Hrm_EmployeeInfo1 = new HashSet<Hrm_EmployeeInfo>();
        }
    
        public string UPAZ_CODE { get; set; }
        public string UPAZ_NAME { get; set; }
        public string DIST_CODE { get; set; }
        public System.DateTime CREATED { get; set; }
        public System.DateTime MODIFIED { get; set; }
        public Nullable<decimal> IDCOL_ThanaID { get; set; }
        public string IDCOL_ThanaName { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Common_DistrictInfo Common_DistrictInfo { get; set; }
        public virtual ICollection<Hrm_EmployeeInfo> Hrm_EmployeeInfo { get; set; }
        public virtual ICollection<Hrm_EmployeeInfo> Hrm_EmployeeInfo1 { get; set; }
    }
}
