//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    
    public partial class GetEmployeeTransferredButNotYetAccepted
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public string TransferFromLocation { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string NoteForTransfer { get; set; }
    }
}
