//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_EmployeeTransferAdditionalInfo
    {
        public string EmployeeID { get; set; }
        public byte TransferSeqNo { get; set; }
        public Nullable<System.DateTime> RequisitionReceivedOn { get; set; }
        public string OfficeOrderNo { get; set; }
        public Nullable<System.DateTime> OfficeOrderDate { get; set; }
        public Nullable<System.DateTime> TransferReleaseDate { get; set; } 
        public string ResponsibilityHandoverTo { get; set; }
        public string ResponsibilityTakenoverFrom { get; set; }
        public string ReasonForLateTransferRelease { get; set; }
        public string ReasonForLateTransferJoining { get; set; }
        public Nullable<System.DateTime> ActualTransferReleaseDate { get; set; }
        public Nullable<System.DateTime> ActualTransferJoiningDate { get; set; }
        public string NewOperationalRole { get; set; }
    
        public virtual Hrm_EmployeeInfo Hrm_EmployeeInfo { get; set; }
        public virtual Hrm_EmployeeTransfer Hrm_EmployeeTransfer { get; set; }
    }
}
