//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_EmployeeTransfer
    {
        public string EmployeeID { get; set; }
        public byte TransferSeqNo { get; set; }
        public System.DateTime TransferDate { get; set; }
        public string TransferFromLocation { get; set; }
        public string TransferToLocation { get; set; }
        public bool IsItLastTransfer { get; set; }
        public string NoteForTransfer { get; set; }
        public bool IsTransferAccepted { get; set; }
        public string RefAEProjectCode { get; set; }
        public string RefAETransNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
        public virtual Common_LocationInfo Common_LocationInfo1 { get; set; }
        public virtual Common_LocationInfo Common_LocationInfo2 { get; set; }
        public virtual Hrm_EmployeeInfo Hrm_EmployeeInfo { get; set; }
        public virtual Hrm_LocationWiseEmployee Hrm_LocationWiseEmployee { get; set; }
        public virtual Hrm_EmployeeTransferAdditionalInfo Hrm_EmployeeTransferAdditionalInfo { get; set; }
    }
}
