//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_EmployeeWiseBankAccount
    {
        public string EmployeeID { get; set; }
        public string BankID { get; set; }
        public string BankBranchID { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountType { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> AccountOpeningDate { get; set; }
        public string SalaryLocationCode { get; set; }
        public string SalaryDisbursementBankAccountNumber { get; set; }
        public string SalaryDisbursementBranchName { get; set; }
        public string Remarks { get; set; }
        public byte Status { get; set; }
    
        public virtual Hrm_EmployeeInfo Hrm_EmployeeInfo { get; set; }
    }
}
