//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_EmployeeNDateWiseTADAEntry
    {
        public string YearMonth { get; set; }
        public string LocationCode { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime DateOfTADA { get; set; }
        public decimal TAAmount { get; set; }
        public string ParticularsForTA { get; set; }
        public decimal DAAmount { get; set; }
        public string ParticularsForDA { get; set; }
        public Nullable<byte> DaysOfPendingEntry { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte Status { get; set; }
    
        public virtual Hrm_LocationWiseEmployee Hrm_LocationWiseEmployee { get; set; }
    }
}
