//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_OperationalRole
    {
        public Hrm_OperationalRole()
        {
            this.Hrm_HierarchicalDesignationVsOperationalRole = new HashSet<Hrm_HierarchicalDesignationVsOperationalRole>();
        }
    
        public string OperationalRoleID { get; set; }
        public string OperationalRoleName { get; set; }
        public Nullable<byte> SortingOrder { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual ICollection<Hrm_HierarchicalDesignationVsOperationalRole> Hrm_HierarchicalDesignationVsOperationalRole { get; set; }
    }
}
