//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_EmployeeWiseSalaryStructureDetails
    {
        public string EmployeeID { get; set; }
        public byte SalaryStructureSeqNo { get; set; }
        public string SalaryComponentID { get; set; }
        public string RefHDesignationID { get; set; }
        public string RefEmploymentTypeID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Hrm_EmployeeWiseSalaryStructureMaster Hrm_EmployeeWiseSalaryStructureMaster { get; set; }
        public virtual Hrm_HierarchicalDesignationNEmploymentTypeWisePayBandStructure Hrm_HierarchicalDesignationNEmploymentTypeWisePayBandStructure { get; set; }
        public virtual Hrm_Validation_EmployeeWiseDesignationVsEmploymentType Hrm_Validation_EmployeeWiseDesignationVsEmploymentType { get; set; }
    }
}
