//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_EmployeeInfo
    {
        public Hrm_EmployeeInfo()
        {
            this.Hrm_EmployeeTransfer = new HashSet<Hrm_EmployeeTransfer>();
            this.Hrm_LocationWiseEmployee1 = new HashSet<Hrm_LocationWiseEmployee>();
            this.Hrm_Validation_EmployeeWiseDesignationVsEmploymentType1 = new HashSet<Hrm_Validation_EmployeeWiseDesignationVsEmploymentType>();
            this.Hrm_EmployeeTransferAdditionalInfo = new HashSet<Hrm_EmployeeTransferAdditionalInfo>();
        }
    
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeFathersName { get; set; }
        public string EmployeeMothersName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string PlaceOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string HighestEducation { get; set; }
        public string MajorSubject { get; set; }
        public string BloodGroup { get; set; }
        public string NationalIDCard { get; set; }
        public string EmailID { get; set; }
        public string PresentDistrictCode { get; set; }
        public string PresentUpazillaCode { get; set; }
        public string PresentPoliceStation { get; set; }
        public string PresentPostOffice { get; set; }
        public string PresentStreetOrVillage { get; set; }
        public string PresentHouseNo { get; set; }
        public string PresentMobileNo { get; set; }
        public string PresentPhone { get; set; }
        public string PermanentDistrictCode { get; set; }
        public string PermanentUpazillaCode { get; set; }
        public string PermanentPoliceStation { get; set; }
        public string PermanentPostOffice { get; set; }
        public string PermanentStreetVillage { get; set; }
        public string PermanentHouseNo { get; set; }
        public string PermanentMobileNo { get; set; }
        public string PermanentPhone { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string LastDesignation { get; set; }
        public string LastOperationalRole { get; set; }
        public string LastDepartment { get; set; }
        public string LastSection { get; set; }
        public string LastEmploymentType { get; set; }
        public Nullable<byte> LastSalaryStructureSeqNo { get; set; }
        public string ModeOfSalaryPayment { get; set; }
        public Nullable<byte> ProbationPeriodInMonth { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string LastLocationCode { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> StatusChangedDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public string EmployeeSpouseName { get; set; }
        public string SpouseBloodGroup { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string DrivingLicenseNo { get; set; }
        public Nullable<byte> ContractualPeriodInMonth { get; set; }
    
        public virtual Common_DistrictInfo Common_DistrictInfo { get; set; }
        public virtual Common_DistrictInfo Common_DistrictInfo1 { get; set; }
        public virtual Common_DistrictInfo Common_DistrictInfo2 { get; set; }
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
        public virtual Common_UpazillaInfo Common_UpazillaInfo { get; set; }
        public virtual Common_UpazillaInfo Common_UpazillaInfo1 { get; set; }
        public virtual Hrm_BloodGroupInfo Hrm_BloodGroupInfo { get; set; }
        public virtual Hrm_DepartmentInfo Hrm_DepartmentInfo { get; set; }
        public virtual Hrm_EducationInfo Hrm_EducationInfo { get; set; }
        public virtual Hrm_EmploymentTypeInfo Hrm_EmploymentTypeInfo { get; set; }
        public virtual Hrm_HierarchicalDesignation Hrm_HierarchicalDesignation { get; set; }
        public virtual Hrm_HierarchicalDesignationVsOperationalRole Hrm_HierarchicalDesignationVsOperationalRole { get; set; }
        public virtual Hrm_LocationWiseEmployee Hrm_LocationWiseEmployee { get; set; }
        public virtual Hrm_MajorSubject Hrm_MajorSubject { get; set; }
        public virtual Hrm_MaritalStatusInfo Hrm_MaritalStatusInfo { get; set; }
        public virtual Hrm_ReligionInfo Hrm_ReligionInfo { get; set; }
        public virtual Hrm_SubDepartmentOrSection Hrm_SubDepartmentOrSection { get; set; }
        public virtual Hrm_Validation_EmployeeWiseDesignationVsEmploymentType Hrm_Validation_EmployeeWiseDesignationVsEmploymentType { get; set; }
        public virtual ICollection<Hrm_EmployeeTransfer> Hrm_EmployeeTransfer { get; set; }
        public virtual ICollection<Hrm_LocationWiseEmployee> Hrm_LocationWiseEmployee1 { get; set; }
        public virtual ICollection<Hrm_Validation_EmployeeWiseDesignationVsEmploymentType> Hrm_Validation_EmployeeWiseDesignationVsEmploymentType1 { get; set; }
        public virtual Hrm_EmployeeWiseBankAccount Hrm_EmployeeWiseBankAccount { get; set; }
        public virtual Hrm_EmployeeWiseSalaryStructureMaster Hrm_EmployeeWiseSalaryStructureMaster { get; set; }
        public virtual ICollection<Hrm_EmployeeTransferAdditionalInfo> Hrm_EmployeeTransferAdditionalInfo { get; set; }
    }
}
