//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_Validation_EmployeeWiseDesignationVsEmploymentType
    {
        public Hrm_Validation_EmployeeWiseDesignationVsEmploymentType()
        {
            this.Hrm_EmployeeInfo = new HashSet<Hrm_EmployeeInfo>();
            this.Hrm_EmployeeWiseSalaryStructureDetails = new HashSet<Hrm_EmployeeWiseSalaryStructureDetails>();
            this.Hrm_EmployeeWiseSalaryStructureMaster = new HashSet<Hrm_EmployeeWiseSalaryStructureMaster>();
        }
    
        public string EmployeeID { get; set; }
        public string HDesignationID { get; set; }
        public string EmploymentTypeID { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Hrm_EmployeeInfo> Hrm_EmployeeInfo { get; set; }
        public virtual Hrm_EmployeeInfo Hrm_EmployeeInfo1 { get; set; }
        public virtual ICollection<Hrm_EmployeeWiseSalaryStructureDetails> Hrm_EmployeeWiseSalaryStructureDetails { get; set; }
        public virtual ICollection<Hrm_EmployeeWiseSalaryStructureMaster> Hrm_EmployeeWiseSalaryStructureMaster { get; set; }
    }
}
