//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_HierarchicalDesignationNEmploymentTypeWisePayBandStructure
    {
        public Hrm_HierarchicalDesignationNEmploymentTypeWisePayBandStructure()
        {
            this.Hrm_EmployeeWiseSalaryStructureDetails = new HashSet<Hrm_EmployeeWiseSalaryStructureDetails>();
        }
    
        public string HDesignationID { get; set; }
        public string EmploymentTypeID { get; set; }
        public string SalaryComponentID { get; set; }
        public Nullable<decimal> MinBandAmountFrom { get; set; }
        public Nullable<decimal> MinBandAmountTo { get; set; }
        public Nullable<decimal> MidBandAmountFrom { get; set; }
        public Nullable<decimal> MidBandAmountTo { get; set; }
        public Nullable<decimal> MaxBandAmountFrom { get; set; }
        public Nullable<decimal> MaxBandAmountTo { get; set; }
        public Nullable<decimal> FixedAmount { get; set; }
        public string Remarks { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Hrm_EmployeeWiseSalaryStructureDetails> Hrm_EmployeeWiseSalaryStructureDetails { get; set; }
        public virtual Hrm_EmploymentTypeInfo Hrm_EmploymentTypeInfo { get; set; }
        public virtual Hrm_HierarchicalDesignation Hrm_HierarchicalDesignation { get; set; }
    }
}
