//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_DepartmentInfo
    {
        public Hrm_DepartmentInfo()
        {
            this.Hrm_EmployeeInfo = new HashSet<Hrm_EmployeeInfo>();
            this.Hrm_SubDepartmentOrSection = new HashSet<Hrm_SubDepartmentOrSection>();
        }
    
        public string DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<byte> SortingOrder { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual ICollection<Hrm_EmployeeInfo> Hrm_EmployeeInfo { get; set; }
        public virtual ICollection<Hrm_SubDepartmentOrSection> Hrm_SubDepartmentOrSection { get; set; }
    }
}
