//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_EmploymentTypeInfo
    {
        public Hrm_EmploymentTypeInfo()
        {
            this.Hrm_EmployeeInfo = new HashSet<Hrm_EmployeeInfo>();
            this.Hrm_EmployeeWiseSalaryStructureMaster = new HashSet<Hrm_EmployeeWiseSalaryStructureMaster>();
            this.Hrm_HierarchicalDesignationNEmploymentTypeWisePayBandStructure = new HashSet<Hrm_HierarchicalDesignationNEmploymentTypeWisePayBandStructure>();
        }
    
        public string EmploymentTypeID { get; set; }
        public string EmploymentTypeDescription { get; set; }
        public Nullable<byte> SortingOrder { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual ICollection<Hrm_EmployeeInfo> Hrm_EmployeeInfo { get; set; }
        public virtual ICollection<Hrm_EmployeeWiseSalaryStructureMaster> Hrm_EmployeeWiseSalaryStructureMaster { get; set; }
        public virtual ICollection<Hrm_HierarchicalDesignationNEmploymentTypeWisePayBandStructure> Hrm_HierarchicalDesignationNEmploymentTypeWisePayBandStructure { get; set; }
    }
}
