//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarHRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_LocationWiseSalespersonForHOnZO
    {
        public string LocationCode { get; set; }
        public string SalespersonCode { get; set; }
        public string Status { get; set; }
    }
}
