//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aud_AdjustmentReasonCodes
    {
        public string ReasonCode { get; set; }
        public string ReasonPurposeID { get; set; }
        public string ReasonDescription { get; set; }
        public byte OrderSerialNo { get; set; }
        public string ReasonForUserOrAuditor { get; set; }
        public bool ReasonForNew { get; set; }
        public bool ReasonForSR { get; set; }
        public bool ReasonForCSI { get; set; }
        public bool ReasonForPlusOrMinusQty { get; set; }
        public bool ReasonForPlusQtyOnly { get; set; }
        public bool ReasonForMinusQtyOnly { get; set; }
        public string ReasonForModule { get; set; }
        public string EmployeeMappingValidity { get; set; }
        public byte Status { get; set; }
    }
}
