//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aud_AuditAdjustmentObservationOnSalesAgreement
    {
        public string LocationCode { get; set; }
        public string YearMonth { get; set; }
        public string CustomerCode { get; set; }
        public string DataStatusFlag { get; set; }
        public string AuditSeqNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public string PackageCapacity { get; set; }
        public string PackageLight { get; set; }
        public string PackageCode { get; set; }
        public string ModeOfPaymentID { get; set; }
        public string CustomerType { get; set; }
        public Nullable<decimal> PackagePrice { get; set; }
        public string DownPaymentID { get; set; }
        public Nullable<decimal> DownPaymentAmount { get; set; }
        public string ServiceChargeID { get; set; }
        public Nullable<byte> STDServiceChargePercentage { get; set; }
        public string CashMemoNo { get; set; }
        public string CashMemoUsesID { get; set; }
        public string RefMemoNo { get; set; }
        public Nullable<bool> IsReSales { get; set; }
        public Nullable<byte> StoreLocationForPanel { get; set; }
        public string PanelItemCode { get; set; }
        public string PanelSerialNo { get; set; }
        public Nullable<byte> StoreLocationForBattery { get; set; }
        public string BatteryItemCode { get; set; }
        public string BatterySerialNo { get; set; }
        public string PanelStructureItemCode { get; set; }
        public string HolderItemCode { get; set; }
        public string Remarks { get; set; }
        public byte Status { get; set; }
        public Nullable<double> HolderQty { get; set; }
        public Nullable<double> TubeLightQty { get; set; }
        public Nullable<double> LEDTubeQty { get; set; }
        public Nullable<double> LED_2Qty { get; set; }
        public Nullable<double> LED_3Qty { get; set; }
        public Nullable<double> LED_5Qty { get; set; }
        public Nullable<double> CFLQty { get; set; }
        public string LampShadeCode { get; set; }
        public Nullable<double> LampShadeQty { get; set; }
        public string Circuit_LampCktCode { get; set; }
        public Nullable<double> Circuit_LampCktQty { get; set; }
        public Nullable<double> ChargeController_10AQty { get; set; }
        public Nullable<double> ChargeController_6AQty { get; set; }
        public Nullable<double> Cable7076Qty { get; set; }
        public Nullable<double> Cable4076Qty { get; set; }
        public Nullable<double> Cable2376Qty { get; set; }
        public Nullable<double> Cable1476Qty { get; set; }
        public Nullable<double> SwitchQty { get; set; }
        public Nullable<double> SwitchBoardBoxQty { get; set; }
        public string ProgramCode { get; set; }
    
        public virtual Sal_Validation_CapacityVsLight Sal_Validation_CapacityVsLight { get; set; }
        public virtual Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage { get; set; }
        public virtual Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy { get; set; }
        public virtual Sal_SalesAgreement Sal_SalesAgreement { get; set; }
        public virtual Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy { get; set; }
    }
}
