//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aud_AuditAdjustmentRelatedChallanOrMRRForReference
    {
        public string LocationCode { get; set; }
        public string DocSeqNo { get; set; }
        public string AuditSeqNo { get; set; }
        public string RefChallanSeqNo { get; set; }
        public string RefMRRSeqNo { get; set; }
        public string ReasonCode { get; set; }
        public string ResponsibleEmployeeID { get; set; }
        public Nullable<decimal> AuditClaimAmount { get; set; }
        public string Remarks { get; set; }
    
        public virtual Inv_ChallanMaster Inv_ChallanMaster { get; set; }
        public virtual Inv_MRRMaster Inv_MRRMaster { get; set; }
    }
}
