//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aud_AuditAdjustmentRelatedCollectionFromCustomers
    {
        public string CustomerCode { get; set; }
        public string YearMonth { get; set; }
        public byte SerialNo { get; set; }
        public string AuditSeqNo { get; set; }
        public string CollectionInUnit { get; set; }
        public string ReasonCode { get; set; }
        public string ResponsibleEmployeeID { get; set; }
        public string Remarks { get; set; }
    
        public virtual Sal_CollectionFromCustomers Sal_CollectionFromCustomers { get; set; }
    }
}
