//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class ChallanInboxForChallanWithMRR
    {
        public string LocationCode { get; set; }
        public string ChallanSeqNo { get; set; }
        public string ReceivedChallan { get; set; }
        public System.DateTime ChallanDate { get; set; }
    }
}
