//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_Sys_SystemSettings
    {
        public string CompanyName { get; set; }
        public string BaseCurrency { get; set; }
        public bool IsCashMemoManagementEnabled { get; set; }
    }
}
