//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_UnitInfo
    {
        public Common_UnitInfo()
        {
            this.Sal_CustomerTrainingSchedule = new HashSet<Sal_CustomerTrainingSchedule>();
            this.Sal_SalesAgreement = new HashSet<Sal_SalesAgreement>();
            this.Sal_SalesAgreementPrePost = new HashSet<Sal_SalesAgreementPrePost>();
            this.Sal_Validation_UnitVsUpazilla = new HashSet<Sal_Validation_UnitVsUpazilla>();
            this.Sal_CustomerTrainingTransMaster = new HashSet<Sal_CustomerTrainingTransMaster>();
            this.Sal_Customer = new HashSet<Sal_Customer>();
            this.Sal_CustomerPrePost = new HashSet<Sal_CustomerPrePost>();
            this.Sal_CustomerInfoBackup = new HashSet<Sal_CustomerInfoBackup>();
            this.Sal_SalesAgreementPrePost_DataFromExternalSources = new HashSet<Sal_SalesAgreementPrePost_DataFromExternalSources>();
        }
    
        public string Unit_Code { get; set; }
        public string Unit_Code1 { get; set; }
        public string Unit_Name { get; set; }
        public string Reg_Code { get; set; }
        public System.DateTime CREATED { get; set; }
        public System.DateTime MODIFIED { get; set; }
        public string CUSTCODE_PREFIX { get; set; }
        public Nullable<decimal> IDCOL_BranchID { get; set; }
        public string IDCOL_BranchName { get; set; }
        public short LastUsedCustomerSerial { get; set; }
        public string UM_CellNo { get; set; }
        public Nullable<bool> IsItPoorCollectionEfficiencyUnit { get; set; }
        public Nullable<byte> MinNoOfCustomerForAnFPR { get; set; }
        public Nullable<short> MaxNoOfCustomerForAnFPR { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CustomerMobileNoMandatoryFrom { get; set; }
        public string ManagersEmailID { get; set; }
    
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
        public virtual Common_RegionInfo Common_RegionInfo { get; set; }
        public virtual ICollection<Sal_CustomerTrainingSchedule> Sal_CustomerTrainingSchedule { get; set; }
        public virtual ICollection<Sal_SalesAgreement> Sal_SalesAgreement { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost> Sal_SalesAgreementPrePost { get; set; }
        public virtual ICollection<Sal_Validation_UnitVsUpazilla> Sal_Validation_UnitVsUpazilla { get; set; }
        public virtual ICollection<Sal_CustomerTrainingTransMaster> Sal_CustomerTrainingTransMaster { get; set; }
        public virtual ICollection<Sal_Customer> Sal_Customer { get; set; }
        public virtual ICollection<Sal_CustomerPrePost> Sal_CustomerPrePost { get; set; }
        public virtual ICollection<Sal_CustomerInfoBackup> Sal_CustomerInfoBackup { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost_DataFromExternalSources> Sal_SalesAgreementPrePost_DataFromExternalSources { get; set; }
    }
}
