//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_ProgramInfo
    {
        public Common_ProgramInfo()
        {
            this.Common_ProjectInfo = new HashSet<Common_ProjectInfo>();
            this.Sal_Validation_ProgramVsCustomerTypeNModeOfPayment = new HashSet<Sal_Validation_ProgramVsCustomerTypeNModeOfPayment>();
        }
    
        public string Prog_Code { get; set; }
        public string Prog_Name { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual ICollection<Common_ProjectInfo> Common_ProjectInfo { get; set; }
        public virtual ICollection<Sal_Validation_ProgramVsCustomerTypeNModeOfPayment> Sal_Validation_ProgramVsCustomerTypeNModeOfPayment { get; set; }
    }
}
