//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_DistrictInfo
    {
        public Common_DistrictInfo()
        {
            this.Common_UpazillaInfo = new HashSet<Common_UpazillaInfo>();
            this.Sal_Customer = new HashSet<Sal_Customer>();
            this.Sal_CustomerPrePost = new HashSet<Sal_CustomerPrePost>();
            this.Sal_CustomerInfoBackup = new HashSet<Sal_CustomerInfoBackup>();
        }
    
        public string DIST_CODE { get; set; }
        public string DIST_NAME { get; set; }
        public System.DateTime CREATED { get; set; }
        public System.DateTime MODIFIED { get; set; }
    
        public virtual ICollection<Common_UpazillaInfo> Common_UpazillaInfo { get; set; }
        public virtual ICollection<Sal_Customer> Sal_Customer { get; set; }
        public virtual ICollection<Sal_CustomerPrePost> Sal_CustomerPrePost { get; set; }
        public virtual ICollection<Sal_CustomerInfoBackup> Sal_CustomerInfoBackup { get; set; }
    }
}
