//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_LocationInfo
    {
        public Common_LocationInfo()
        {
            this.Inv_ChallanMaster = new HashSet<Inv_ChallanMaster>();
            this.Inv_ChallanWithMultipleLocations = new HashSet<Inv_ChallanWithMultipleLocations>();
            this.Inv_ChallanWithMultipleLocations1 = new HashSet<Inv_ChallanWithMultipleLocations>();
            this.Inv_ItemStockByLocation = new HashSet<Inv_ItemStockByLocation>();
            this.Hrm_LocationWiseEmployee = new HashSet<Hrm_LocationWiseEmployee>();
            this.Common_PeriodOpenClose = new HashSet<Common_PeriodOpenClose>();
            this.Fix_EmployeeWiseFixedAssetsAllocation = new HashSet<Fix_EmployeeWiseFixedAssetsAllocation>();
            this.Inv_MRRMaster = new HashSet<Inv_MRRMaster>();
            this.Inv_ItemNItemCategoryWithSerialNoMaster = new HashSet<Inv_ItemNItemCategoryWithSerialNoMaster>();
            this.Inv_RouteDetail = new HashSet<Inv_RouteDetail>();
            this.Sal_SparePartsSalesMaster = new HashSet<Sal_SparePartsSalesMaster>();
            this.Sal_SparePartsSales_DataFromExternalSources = new HashSet<Sal_SparePartsSales_DataFromExternalSources>();
        }
    
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public byte LocationType { get; set; }
        public string ParentLocation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public byte Status { get; set; }
        public Nullable<bool> TempIsInventoryStockUpdateFinish { get; set; }
        public Nullable<byte> BackDayAllowedForTransaction { get; set; }
        public string NewLocationCode { get; set; }
        public Nullable<decimal> IDCOL_BranchID { get; set; }
        public string IDCOL_BranchName { get; set; }
        public string ManagersMobileNo { get; set; }
        public Nullable<bool> IsItPoorCollectionEfficiencyUnit { get; set; }
        public string ManagersEmployeeID { get; set; }
        public string GeographicalCategory { get; set; }
        public string BaseOfficeLocationCode { get; set; }
    
        public virtual ICollection<Inv_ChallanMaster> Inv_ChallanMaster { get; set; }
        public virtual ICollection<Inv_ChallanWithMultipleLocations> Inv_ChallanWithMultipleLocations { get; set; }
        public virtual ICollection<Inv_ChallanWithMultipleLocations> Inv_ChallanWithMultipleLocations1 { get; set; }
        public virtual ICollection<Inv_ItemStockByLocation> Inv_ItemStockByLocation { get; set; }
        public virtual Common_Sys_LocationType Common_Sys_LocationType { get; set; }
        public virtual ICollection<Hrm_LocationWiseEmployee> Hrm_LocationWiseEmployee { get; set; }
        public virtual ICollection<Common_PeriodOpenClose> Common_PeriodOpenClose { get; set; }
        public virtual Common_RegionInfo Common_RegionInfo { get; set; }
        public virtual Common_ZoneInfo Common_ZoneInfo { get; set; }
        public virtual ICollection<Fix_EmployeeWiseFixedAssetsAllocation> Fix_EmployeeWiseFixedAssetsAllocation { get; set; }
        public virtual ICollection<Inv_MRRMaster> Inv_MRRMaster { get; set; }
        public virtual ICollection<Inv_ItemNItemCategoryWithSerialNoMaster> Inv_ItemNItemCategoryWithSerialNoMaster { get; set; }
        public virtual ICollection<Inv_RouteDetail> Inv_RouteDetail { get; set; }
        public virtual Common_UnitInfo Common_UnitInfo { get; set; }
        public virtual ICollection<Sal_SparePartsSalesMaster> Sal_SparePartsSalesMaster { get; set; }
        public virtual ICollection<Sal_SparePartsSales_DataFromExternalSources> Sal_SparePartsSales_DataFromExternalSources { get; set; }
    }
}
