//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_ProjectInfo
    {
        public Common_ProjectInfo()
        {
            this.Sal_PackageOrItemCapacity = new HashSet<Sal_PackageOrItemCapacity>();
        }
    
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string Project_Status { get; set; }
        public string Prog_Code { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
    
        public virtual Common_ProgramInfo Common_ProgramInfo { get; set; }
        public virtual ICollection<Sal_PackageOrItemCapacity> Sal_PackageOrItemCapacity { get; set; }
    }
}
