//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_PeriodOpenClose
    {
        public string LocationCode { get; set; }
        public System.DateTime CalenderDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string OpenBy { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CloseBy { get; set; }
        public Nullable<bool> IsDayOpenForDailyEntry { get; set; }
        public string Status { get; set; }
    
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
    }
}
