//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class CustomerTrainingSummary
    {
        public string Zone_Name { get; set; }
        public string Region_Name { get; set; }
        public string Unit_Name { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public byte NoOfParticipantAttend { get; set; }
        public decimal TrainingAllowance { get; set; }
        public decimal EntertainmentExp { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    }
}
