//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class CustomerInfoNPackageDetailsForSystemReturn
    {
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public System.DateTime AgreementDate { get; set; }
        public Nullable<int> UsagesMonth { get; set; }
        public string PackageName { get; set; }
        public decimal PackagePrice { get; set; }
        public decimal DownPaymentAmount { get; set; }
        public decimal TotalPrincipalReceivable { get; set; }
        public decimal TotalServiceChargeReceivable { get; set; }
        public decimal TotalPrincipalPlusServiceChargeReceivable { get; set; }
        public Nullable<decimal> TotalPrincipalUpToCurrentMonth { get; set; }
        public Nullable<decimal> TotalServiceCHargeUpToCurrentMonth { get; set; }
        public decimal InstallmentSizeServiceCharge { get; set; }
        public Nullable<decimal> UsageCharge { get; set; }
        public Nullable<decimal> TotalRecoverdDPWithInstallment { get; set; }
    }
}
