//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class CustomerTrainingInfo
    {
        public string CustomerCode { get; set; }
        public string UnitCode { get; set; }
        public string CustomerName { get; set; }
        public string Village { get; set; }
        public string DistrictName { get; set; }
        public bool IsCustomerTrained { get; set; }
        public Nullable<System.DateTime> CustomerTrainingDate { get; set; }
        public string PanelSerialNo { get; set; }
    }
}
