//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class CustomerLedgerReport
    {
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string PanelSerialNo { get; set; }
        public string BatterySerialNo { get; set; }
        public string CustomerType { get; set; }
        public string PhoneNo { get; set; }
        public System.DateTime AgreementDate { get; set; }
        public string Package { get; set; }
        public string PaymentMode { get; set; }
        public decimal PackagePrice { get; set; }
        public decimal DiscountAmount { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public decimal AmountAfterDiscount { get; set; }
        public decimal DownPaymentAmount { get; set; }
        public byte STDDownPaymentPercentage { get; set; }
        public decimal TotalPrincipalReceivable { get; set; }
        public byte ServiceChargePercentage { get; set; }
        public decimal TotalServiceChargeReceivable { get; set; }
        public decimal InstallmentSize { get; set; }
        public decimal TotalPrincipalPlusServiceChargeReceivable { get; set; }
        public string CollectionType { get; set; }
        public string RefMemoNo { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public Nullable<decimal> CollectionAmount { get; set; }
        public Nullable<decimal> OverdueOrAdvanceBalance { get; set; }
        public Nullable<decimal> OutstandingBalance { get; set; }
        public string Status { get; set; }
        public string YearMonth { get; set; }
        public Nullable<byte> SerialNo { get; set; }
    }
}
