//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class DailyZonalPerformanceMonitoring
    {
        public string LocationName { get; set; }
        public Nullable<int> Sales_Monthly_Target_Qty { get; set; }
        public double Sales_Monthly_Achievement_Percent { get; set; }
        public int Sales_UpToDate_Target_Qty { get; set; }
        public int Sales_UpToDate_Achievement_Qty { get; set; }
        public double Sales_UpToDate_Achievement_Percent { get; set; }
        public int Sales_OnTheDate_Target_Qty { get; set; }
        public int Sales_OnTheDate_Achievement_Qty { get; set; }
        public decimal Collection_Monthly_CC_Receivable_InMillion { get; set; }
        public decimal Collection_Monthly_Total_Overdue_InMillion { get; set; }
        public decimal Collection_UpToDate_Target_CC_Receivable_InMillion { get; set; }
        public decimal Collection_UpToDate_Target_Overdue_Receivable_InMillion { get; set; }
        public decimal Collection_UpToDate_Achievement_CC_Recovered_InMillion { get; set; }
        public decimal Collection_UpToDate_Achievement_Overdue_Recovered_InMillion { get; set; }
        public int DRF_New_Qty { get; set; }
        public int DRF_Old_Qty { get; set; }
        public int System_Return_UpToDate { get; set; }
        public double Collection_UpToDate_Achievement_CC_Plus_OD_Percent { get; set; }
        public int Resales_UpToDate { get; set; }
    }
}
