//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fix_EmployeeWiseFixedAssetsAllocation
    {
        public Fix_EmployeeWiseFixedAssetsAllocation()
        {
            this.Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo = new HashSet<Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo>();
        }
    
        public byte StoreLocation { get; set; }
        public string LocationCode { get; set; }
        public string ItemCode { get; set; }
        public string EmployeeID { get; set; }
        public string AllocationSeqNo { get; set; }
        public System.DateTime AllocationDate { get; set; }
        public short AllocatedQuantity { get; set; }
        public string AllocatedBy { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte Status { get; set; }
    
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
        public virtual Inv_ItemMaster Inv_ItemMaster { get; set; }
        public virtual Inv_ItemStockByLocation Inv_ItemStockByLocation { get; set; }
        public virtual ICollection<Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo> Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo { get; set; }
        public virtual Hrm_LocationWiseEmployee Hrm_LocationWiseEmployee { get; set; }
    }
}
