//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class GetLocationNEmployeeWiseDailyEntry
    {
        public string LocationCode { get; set; }
        public Nullable<int> LocationSalesCurrentMonthTarget { get; set; }
        public Nullable<int> LocationSalesAchievementUptoLastDay { get; set; }
        public Nullable<int> LocationSalesAchievementToday { get; set; }
        public string LocationSalesAchievementStatus { get; set; }
        public Nullable<decimal> LocationRegColcCurrentMonthTarget { get; set; }
        public Nullable<decimal> LocationRegColcAchievementUptoLastDay { get; set; }
        public Nullable<decimal> LocationRegColcAchievementToday { get; set; }
        public string LocationRegColcAchievementStatus { get; set; }
        public Nullable<decimal> LocationOverdueColcCurrentMonthTarget { get; set; }
        public Nullable<decimal> LocationOverdueColcAchievementToday { get; set; }
        public Nullable<decimal> LocationOverdueColcAchievementUptoLastDay { get; set; }
        public string LocationOverdueColcAchievementStatus { get; set; }
        public Nullable<int> LocationSystemReturn { get; set; }
        public Nullable<int> LocationSystemReSale { get; set; }
        public Nullable<int> LocationCustomerTraining { get; set; }
        public Nullable<int> LocationBioGasSales { get; set; }
        public Nullable<int> LocationRSFBatterySales { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> EMP_SalesCurrentMonthTarget { get; set; }
        public Nullable<int> EMP_SalesAchievementUptoLastDay { get; set; }
        public Nullable<int> EMP_SalesAchievementToday { get; set; }
        public string EMP_SalesAchievementStatus { get; set; }
        public Nullable<decimal> EMP_RegColcCurrentMonthTarget { get; set; }
        public Nullable<decimal> EMP_RegColcAchievementUptoLastDay { get; set; }
        public Nullable<decimal> EMP_RegColcAchievementToday { get; set; }
        public string EMP_RegColcAchievementStatus { get; set; }
        public Nullable<decimal> EMP_OverdueColcCurrentMonthTarget { get; set; }
        public Nullable<decimal> EMP_OverdueColcAchievementUptoLastDay { get; set; }
        public Nullable<decimal> EMP_OverdueColcAchievementToday { get; set; }
        public string EMP_OverdueColcAchievementStatus { get; set; }
        public Nullable<decimal> EMP_TAToday { get; set; }
        public string EMP_ReasonForTAToday { get; set; }
        public Nullable<bool> EMP_SystemInstallationToday { get; set; }
        public Nullable<bool> EMP_InstallmentCollectionToday { get; set; }
        public Nullable<bool> EMP_CustomerVisitForMarketingToday { get; set; }
        public Nullable<bool> EMP_MaintenanceServicingToday { get; set; }
        public Nullable<bool> EMP_BankOperationToday { get; set; }
        public Nullable<bool> EMP_OfficialVisitToOtherUnitToday { get; set; }
        public Nullable<bool> EMP_MeetingToday { get; set; }
        public Nullable<bool> EMP_WasInLeaveToday { get; set; }
        public Nullable<bool> EMP_DeskWorksToday { get; set; }
        public string EMP_RemarksToday { get; set; }
        public Nullable<decimal> EMP_TATomorrow { get; set; }
        public string EMP_ReasonForTATomorrow { get; set; }
        public Nullable<bool> EMP_SystemInstallationTomorrow { get; set; }
        public Nullable<bool> EMP_InstallmentCollectionTomorrow { get; set; }
        public Nullable<bool> EMP_CustomerVisitForMarketingTomorrow { get; set; }
        public Nullable<bool> EMP_MaintenanceServicingTomorrow { get; set; }
        public Nullable<bool> EMP_BankOperationTomorrow { get; set; }
        public Nullable<bool> EMP_OfficialVisitToOtherUnitTomorrow { get; set; }
        public Nullable<bool> EMP_MeetingTomorrow { get; set; }
        public Nullable<bool> EMP_WillBeInLeaveTomorrow { get; set; }
        public Nullable<bool> EMP_DeskWorksTomorrow { get; set; }
        public string EMP_RemarksTomorrow { get; set; }
    }
}
