//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrm_LocationWiseEmployee
    {
        public Hrm_LocationWiseEmployee()
        {
            this.Sal_LocationNEmployeeWiseDailySalesNCollectionTarget = new HashSet<Sal_LocationNEmployeeWiseDailySalesNCollectionTarget>();
            this.Common_CashMemoBookMaster = new HashSet<Common_CashMemoBookMaster>();
            this.Fix_EmployeeWiseFixedAssetsAllocation = new HashSet<Fix_EmployeeWiseFixedAssetsAllocation>();
        }
    
        public string LocationCode { get; set; }
        public string EmployeeID { get; set; }
        public byte Status { get; set; }
    
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
        public virtual ICollection<Sal_LocationNEmployeeWiseDailySalesNCollectionTarget> Sal_LocationNEmployeeWiseDailySalesNCollectionTarget { get; set; }
        public virtual ICollection<Common_CashMemoBookMaster> Common_CashMemoBookMaster { get; set; }
        public virtual ICollection<Fix_EmployeeWiseFixedAssetsAllocation> Fix_EmployeeWiseFixedAssetsAllocation { get; set; }
    }
}
