//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_MRRDetails
    {
        public Inv_MRRDetails()
        {
            this.Inv_MRRDetailsWithSerialNo = new HashSet<Inv_MRRDetailsWithSerialNo>();
            this.Inv_ItemTransactionDetails = new HashSet<Inv_ItemTransactionDetails>();
        }
    
        public string LocationCode { get; set; }
        public string MRRSeqNo { get; set; }
        public byte CompSeqNo { get; set; }
        public string ItemCode { get; set; }
        public double ReceiveQuantity { get; set; }
        public byte ForStoreLocation { get; set; }
        public decimal UnitCost { get; set; }
        public string RefChallanLocationCode { get; set; }
        public string RefChallanSeqNo { get; set; }
        public Nullable<byte> RefChallanCompSeqNo { get; set; }
        public string RefItemTransType { get; set; }
        public string RefItemCategory { get; set; }
    
        public virtual Inv_ChallanDetails Inv_ChallanDetails { get; set; }
        public virtual ICollection<Inv_MRRDetailsWithSerialNo> Inv_MRRDetailsWithSerialNo { get; set; }
        public virtual ICollection<Inv_ItemTransactionDetails> Inv_ItemTransactionDetails { get; set; }
        public virtual Inv_MRRMaster Inv_MRRMaster { get; set; }
    }
}
