//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ItemMaster
    {
        public Inv_ItemMaster()
        {
            this.Sal_SalesItems = new HashSet<Sal_SalesItems>();
            this.Sal_SparePartsSalesItems = new HashSet<Sal_SparePartsSalesItems>();
            this.Fix_EmployeeWiseFixedAssetsAllocation = new HashSet<Fix_EmployeeWiseFixedAssetsAllocation>();
            this.Inv_ItemStockWithSerialNoByLocation = new HashSet<Inv_ItemStockWithSerialNoByLocation>();
            this.Inv_Validation_SubstituteItemNMapping = new HashSet<Inv_Validation_SubstituteItemNMapping>();
            this.Inv_Validation_SubstituteItemNMapping1 = new HashSet<Inv_Validation_SubstituteItemNMapping>();
            this.Sal_SalesItemsPrePost = new HashSet<Sal_SalesItemsPrePost>();
        }
    
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public string ItemCategory { get; set; }
        public string ItemCapacity { get; set; }
        public string ItemModel { get; set; }
        public Nullable<short> UKSeqNoForFANStationary { get; set; }
        public decimal AverageUnitCost { get; set; }
        public string FastOrSlowMoving { get; set; }
        public string IDCOL_Model { get; set; }
        public string IDCOL_Capacity { get; set; }
        public byte Status { get; set; }
        public Nullable<bool> IsItAWarrantyItem { get; set; }
        public Nullable<byte> GeneralWarrantyPeriodInMonth { get; set; }
        public Nullable<byte> VendorWarrantyPeriodInMonth { get; set; }
        public Nullable<bool> IsItAObsoleteItem { get; set; }
    
        public virtual Inv_ItemCategorySubCategory Inv_ItemCategorySubCategory { get; set; }
        public virtual Inv_ItemModel Inv_ItemModel { get; set; }
        public virtual Inv_Sys_ItemType Inv_Sys_ItemType { get; set; }
        public virtual Sal_PackageOrItemCapacity Sal_PackageOrItemCapacity { get; set; }
        public virtual ICollection<Sal_SalesItems> Sal_SalesItems { get; set; }
        public virtual ICollection<Sal_SparePartsSalesItems> Sal_SparePartsSalesItems { get; set; }
        public virtual ICollection<Fix_EmployeeWiseFixedAssetsAllocation> Fix_EmployeeWiseFixedAssetsAllocation { get; set; }
        public virtual ICollection<Inv_ItemStockWithSerialNoByLocation> Inv_ItemStockWithSerialNoByLocation { get; set; }
        public virtual ICollection<Inv_Validation_SubstituteItemNMapping> Inv_Validation_SubstituteItemNMapping { get; set; }
        public virtual ICollection<Inv_Validation_SubstituteItemNMapping> Inv_Validation_SubstituteItemNMapping1 { get; set; }
        public virtual ICollection<Sal_SalesItemsPrePost> Sal_SalesItemsPrePost { get; set; }
    }
}
