//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ItemStockWithSerialNoByLocation
    {
        public Inv_ItemStockWithSerialNoByLocation()
        {
            this.Inv_ChallanDetailsWithSerialNo = new HashSet<Inv_ChallanDetailsWithSerialNo>();
            this.Inv_ItemNItemCategoryWithSerialNoMaster = new HashSet<Inv_ItemNItemCategoryWithSerialNoMaster>();
            this.Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo = new HashSet<Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo>();
        }
    
        public byte StoreLocation { get; set; }
        public string LocationCode { get; set; }
        public string ItemCode { get; set; }
        public string ItemSerialNo { get; set; }
        public byte ItemConditionOrStatus { get; set; }
        public bool IsAvailableInStore { get; set; }
        public Nullable<bool> IsItAllocatedToEmployee { get; set; }
        public Nullable<bool> IsItUnderAuditObservation { get; set; }
    
        public virtual ICollection<Inv_ChallanDetailsWithSerialNo> Inv_ChallanDetailsWithSerialNo { get; set; }
        public virtual Inv_ItemMaster Inv_ItemMaster { get; set; }
        public virtual ICollection<Inv_ItemNItemCategoryWithSerialNoMaster> Inv_ItemNItemCategoryWithSerialNoMaster { get; set; }
        public virtual Inv_ItemNItemCategoryWithSerialNoMaster Inv_ItemNItemCategoryWithSerialNoMaster1 { get; set; }
        public virtual Inv_ItemStockByLocation Inv_ItemStockByLocation { get; set; }
        public virtual ICollection<Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo> Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo { get; set; }
    }
}
