//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Sys_ItemType
    {
        public Inv_Sys_ItemType()
        {
            this.Inv_ChallanMaster = new HashSet<Inv_ChallanMaster>();
            this.Inv_ItemCategorySubCategory = new HashSet<Inv_ItemCategorySubCategory>();
            this.Inv_ItemMaster = new HashSet<Inv_ItemMaster>();
            this.Inv_StoreLocation = new HashSet<Inv_StoreLocation>();
            this.Inv_MRRMaster = new HashSet<Inv_MRRMaster>();
        }
    
        public string ItemTypeID { get; set; }
        public string Description { get; set; }
        public byte SortingOrder { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Inv_ChallanMaster> Inv_ChallanMaster { get; set; }
        public virtual ICollection<Inv_ItemCategorySubCategory> Inv_ItemCategorySubCategory { get; set; }
        public virtual ICollection<Inv_ItemMaster> Inv_ItemMaster { get; set; }
        public virtual ICollection<Inv_StoreLocation> Inv_StoreLocation { get; set; }
        public virtual ICollection<Inv_MRRMaster> Inv_MRRMaster { get; set; }
    }
}
