//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ItemTransactionDetails
    {
        public Inv_ItemTransactionDetails()
        {
            this.Inv_ItemTransactionDetailsWithSerialNo = new HashSet<Inv_ItemTransactionDetailsWithSerialNo>();
        }
    
        public byte StoreLocation { get; set; }
        public string YearMonth { get; set; }
        public string LocationCode { get; set; }
        public string ItemCode { get; set; }
        public string MRROrChallanSeqNo { get; set; }
        public string ReceiveOrIssue { get; set; }
        public System.DateTime TransDate { get; set; }
        public string ItemTransTypeID { get; set; }
        public double TransQuantity { get; set; }
        public decimal ValuePerUnit { get; set; }
        public decimal TransValue { get; set; }
        public string EntrySource { get; set; }
        public string RefDocType { get; set; }
        public string RefDocNo { get; set; }
        public string RefMRRSeqNo { get; set; }
        public string RefChallanSeqNo { get; set; }
        public Nullable<byte> RefMRROrChallanCompSeqNo { get; set; }
        public string RefSPSSeqNo { get; set; }
        public string RefCustomerCode { get; set; }
        public string RefVendorID { get; set; }
        public string RefEmployeeID { get; set; }
        public string RefAELocationCode { get; set; }
        public Nullable<System.DateTime> RefAETransDate { get; set; }
        public string RefAEProjectCode { get; set; }
        public string RefAETransNo { get; set; }
        public string RefAEEntrySource { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Inv_ChallanDetails Inv_ChallanDetails { get; set; }
        public virtual Inv_MRRDetails Inv_MRRDetails { get; set; }
        public virtual ICollection<Inv_ItemTransactionDetailsWithSerialNo> Inv_ItemTransactionDetailsWithSerialNo { get; set; }
    }
}
