//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ItemCategorySubCategory
    {
        public Inv_ItemCategorySubCategory()
        {
            this.Inv_ItemMaster = new HashSet<Inv_ItemMaster>();
            this.Inv_ItemModel = new HashSet<Inv_ItemModel>();
            this.Sal_PackageDetail = new HashSet<Sal_PackageDetail>();
        }
    
        public string ItemCategoryID { get; set; }
        public string Description { get; set; }
        public string ItemType { get; set; }
        public string UnitOfMeasure { get; set; }
        public string ParentCategoryID { get; set; }
        public Nullable<bool> IsItAParent { get; set; }
        public Nullable<byte> CategoryLevel { get; set; }
        public bool IsItASerializableItem { get; set; }
        public bool IsItemCapacityAvailable { get; set; }
        public bool IsItemModelAvailable { get; set; }
        public short SortingOrder { get; set; }
        public byte Status { get; set; }
        public bool IsRangeWiseSerialSelectionForChallanEnabled { get; set; }
        public bool IsAllDeliveredSerialSelectionForMRREnabled { get; set; }
    
        public virtual Inv_Sys_ItemType Inv_Sys_ItemType { get; set; }
        public virtual ICollection<Inv_ItemMaster> Inv_ItemMaster { get; set; }
        public virtual ICollection<Inv_ItemModel> Inv_ItemModel { get; set; }
        public virtual ICollection<Sal_PackageDetail> Sal_PackageDetail { get; set; }
    }
}
