//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ItemNItemCategoryWithSerialNoMaster
    {
        public Inv_ItemNItemCategoryWithSerialNoMaster()
        {
            this.Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo = new HashSet<Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo>();
            this.Inv_ChallanDetailsWithSerialNo = new HashSet<Inv_ChallanDetailsWithSerialNo>();
            this.Inv_ItemStockWithSerialNoByLocation1 = new HashSet<Inv_ItemStockWithSerialNoByLocation>();
            this.Inv_ItemTransactionDetailsWithSerialNo1 = new HashSet<Inv_ItemTransactionDetailsWithSerialNo>();
            this.Inv_MRRDetailsWithSerialNo = new HashSet<Inv_MRRDetailsWithSerialNo>();
            this.Sal_SalesAgreementPrePost = new HashSet<Sal_SalesAgreementPrePost>();
            this.Sal_SalesAgreementPrePost1 = new HashSet<Sal_SalesAgreementPrePost>();
            this.Sal_SalesItemsWithSerialNo = new HashSet<Sal_SalesItemsWithSerialNo>();
            this.Sal_SalesItemsWithSerialNoPrePost = new HashSet<Sal_SalesItemsWithSerialNoPrePost>();
            this.Sal_SparePartsSalesItemsWithSerialNo = new HashSet<Sal_SparePartsSalesItemsWithSerialNo>();
            this.Sal_SystemReturnItemsWithSerialNo = new HashSet<Sal_SystemReturnItemsWithSerialNo>();
            this.Sal_SalesAgreement = new HashSet<Sal_SalesAgreement>();
            this.Sal_SalesAgreement1 = new HashSet<Sal_SalesAgreement>();
            this.Sal_SalesAgreementPrePost_DataFromExternalSources = new HashSet<Sal_SalesAgreementPrePost_DataFromExternalSources>();
            this.Sal_SalesAgreementPrePost_DataFromExternalSources1 = new HashSet<Sal_SalesAgreementPrePost_DataFromExternalSources>();
        }
    
        public string ItemCode { get; set; }
        public string ItemSerialNo { get; set; }
        public string ItemCategory { get; set; }
        public Nullable<byte> RefLastStoreLocation { get; set; }
        public string RefLastYearMonth { get; set; }
        public string RefLastLocationCode { get; set; }
        public string RefLastMRROrChallanSeqNo { get; set; }
        public string RefLastReceiveOrIssue { get; set; }
        public Nullable<System.DateTime> RefLastTransDate { get; set; }
        public Nullable<short> RefLastTransSeqNo { get; set; }
        public string RefLastCustomerCode { get; set; }
        public byte ItemConditionOrStatus { get; set; }
        public byte Status { get; set; }
    
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
        public virtual ICollection<Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo> Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo { get; set; }
        public virtual ICollection<Inv_ChallanDetailsWithSerialNo> Inv_ChallanDetailsWithSerialNo { get; set; }
        public virtual Inv_ItemStockWithSerialNoByLocation Inv_ItemStockWithSerialNoByLocation { get; set; }
        public virtual Inv_ItemTransactionDetailsWithSerialNo Inv_ItemTransactionDetailsWithSerialNo { get; set; }
        public virtual ICollection<Inv_ItemStockWithSerialNoByLocation> Inv_ItemStockWithSerialNoByLocation1 { get; set; }
        public virtual ICollection<Inv_ItemTransactionDetailsWithSerialNo> Inv_ItemTransactionDetailsWithSerialNo1 { get; set; }
        public virtual ICollection<Inv_MRRDetailsWithSerialNo> Inv_MRRDetailsWithSerialNo { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost> Sal_SalesAgreementPrePost { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost> Sal_SalesAgreementPrePost1 { get; set; }
        public virtual ICollection<Sal_SalesItemsWithSerialNo> Sal_SalesItemsWithSerialNo { get; set; }
        public virtual ICollection<Sal_SalesItemsWithSerialNoPrePost> Sal_SalesItemsWithSerialNoPrePost { get; set; }
        public virtual ICollection<Sal_SparePartsSalesItemsWithSerialNo> Sal_SparePartsSalesItemsWithSerialNo { get; set; }
        public virtual ICollection<Sal_SystemReturnItemsWithSerialNo> Sal_SystemReturnItemsWithSerialNo { get; set; }
        public virtual ICollection<Sal_SalesAgreement> Sal_SalesAgreement { get; set; }
        public virtual ICollection<Sal_SalesAgreement> Sal_SalesAgreement1 { get; set; }
        public virtual Sal_Customer Sal_Customer { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost_DataFromExternalSources> Sal_SalesAgreementPrePost_DataFromExternalSources { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost_DataFromExternalSources> Sal_SalesAgreementPrePost_DataFromExternalSources1 { get; set; }
    }
}
