//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_StoreLocation
    {
        public Inv_StoreLocation()
        {
            this.Inv_ItemStockByLocation = new HashSet<Inv_ItemStockByLocation>();
        }
    
        public byte StoreLocationID { get; set; }
        public string Description { get; set; }
        public bool IsLocationForRD { get; set; }
        public string ItemType { get; set; }
        public byte SortingOrder { get; set; }
        public string AETrackingFlag { get; set; }
        public byte Status { get; set; }
        public Nullable<bool> IsValidForUnitOffice { get; set; }
        public Nullable<bool> IsValidForZonalOffice { get; set; }
        public Nullable<bool> IsValidForHeadOffice { get; set; }
    
        public virtual ICollection<Inv_ItemStockByLocation> Inv_ItemStockByLocation { get; set; }
        public virtual Inv_Sys_ItemType Inv_Sys_ItemType { get; set; }
    }
}
