//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_VendorInfo
    {
        public Inv_VendorInfo()
        {
            this.Inv_MRRMaster = new HashSet<Inv_MRRMaster>();
        }
    
        public string VendorID { get; set; }
        public string VendorName { get; set; }
        public string VendorAddress { get; set; }
        public Nullable<byte> SortingOrder { get; set; }
        public string ItemTransTypeForIssueForService { get; set; }
        public string ItemTransTypeForReceiveAfterService { get; set; }
        public string ItemTransTypeForReceiveAsPurchase { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Inv_ItemTransactionTypes Inv_ItemTransactionTypes { get; set; }
        public virtual Inv_ItemTransactionTypes Inv_ItemTransactionTypes1 { get; set; }
        public virtual Inv_ItemTransactionTypes Inv_ItemTransactionTypes2 { get; set; }
        public virtual ICollection<Inv_MRRMaster> Inv_MRRMaster { get; set; }
    }
}
