//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ChallanWithMultipleLocations
    {
        public Inv_ChallanWithMultipleLocations()
        {
            this.Inv_ChallanWithMultipleLocationsWithItemWiseDistribution = new HashSet<Inv_ChallanWithMultipleLocationsWithItemWiseDistribution>();
        }
    
        public string ChallanToLocationCode { get; set; }
        public string ChallanFromLocationCode { get; set; }
        public string ChallanSeqNo { get; set; }
        public bool IsReceivedByLocation { get; set; }
    
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
        public virtual Common_LocationInfo Common_LocationInfo1 { get; set; }
        public virtual Inv_ChallanMaster Inv_ChallanMaster { get; set; }
        public virtual ICollection<Inv_ChallanWithMultipleLocationsWithItemWiseDistribution> Inv_ChallanWithMultipleLocationsWithItemWiseDistribution { get; set; }
    }
}
