//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ItemTransactionTypes
    {
        public Inv_ItemTransactionTypes()
        {
            this.Inv_ChallanMaster = new HashSet<Inv_ChallanMaster>();
            this.Inv_MRRMaster = new HashSet<Inv_MRRMaster>();
            this.Inv_VendorInfo = new HashSet<Inv_VendorInfo>();
            this.Inv_VendorInfo1 = new HashSet<Inv_VendorInfo>();
            this.Inv_VendorInfo2 = new HashSet<Inv_VendorInfo>();
        }
    
        public string ItemTransTypeID { get; set; }
        public string ItemTransTypeDesc { get; set; }
        public string ReceiveOrIssue { get; set; }
        public bool IsOnlyForAutoEntry { get; set; }
        public string AEEntrySource { get; set; }
        public bool IsValidForFixedAssets { get; set; }
        public bool IsValidForInventoryItem { get; set; }
        public bool IsValidForConsumableItem { get; set; }
        public byte SortingOrder { get; set; }
        public byte Status { get; set; }
        public string Remarks { get; set; }
        public string StoredProcedureName { get; set; }
        public bool IsItRelatedToVendor { get; set; }
    
        public virtual ICollection<Inv_ChallanMaster> Inv_ChallanMaster { get; set; }
        public virtual ICollection<Inv_MRRMaster> Inv_MRRMaster { get; set; }
        public virtual ICollection<Inv_VendorInfo> Inv_VendorInfo { get; set; }
        public virtual ICollection<Inv_VendorInfo> Inv_VendorInfo1 { get; set; }
        public virtual ICollection<Inv_VendorInfo> Inv_VendorInfo2 { get; set; }
    }
}
