//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ChallanDetailsWithSerialNo
    {
        public Inv_ChallanDetailsWithSerialNo()
        {
            this.Inv_MRRDetailsWithSerialNo = new HashSet<Inv_MRRDetailsWithSerialNo>();
            this.Inv_ItemTransactionDetailsWithSerialNo = new HashSet<Inv_ItemTransactionDetailsWithSerialNo>();
        }
    
        public string LocationCode { get; set; }
        public string ChallanSeqNo { get; set; }
        public byte CompSeqNo { get; set; }
        public string ItemCode { get; set; }
        public string ItemSerialNo { get; set; }
        public Nullable<byte> RefStoreLocation { get; set; }
        public byte Status { get; set; }
    
        public virtual Inv_ChallanDetails Inv_ChallanDetails { get; set; }
        public virtual ICollection<Inv_MRRDetailsWithSerialNo> Inv_MRRDetailsWithSerialNo { get; set; }
        public virtual ICollection<Inv_ItemTransactionDetailsWithSerialNo> Inv_ItemTransactionDetailsWithSerialNo { get; set; }
        public virtual Inv_ItemNItemCategoryWithSerialNoMaster Inv_ItemNItemCategoryWithSerialNoMaster { get; set; }
        public virtual Inv_ItemStockWithSerialNoByLocation Inv_ItemStockWithSerialNoByLocation { get; set; }
    }
}
