//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Validation_SubstituteItemNMapping
    {
        public string ItemCode { get; set; }
        public string SubstituteItemCode { get; set; }
        public string ItemTransType { get; set; }
        public byte StoreLocation { get; set; }
        public byte Status { get; set; }
    
        public virtual Inv_ItemMaster Inv_ItemMaster { get; set; }
        public virtual Inv_ItemMaster Inv_ItemMaster1 { get; set; }
    }
}
