//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_VendorChallanWithItemReferenceToCheck
    {
        public string LocationCode { get; set; }
        public string ChallanYear { get; set; }
        public string VendorRefChallanNo { get; set; }
        public string ItemCode { get; set; }
        public double VendorDeliveryQuantity { get; set; }
        public Nullable<double> ExcessOrShortageDeliveryQuantity { get; set; }
        public Nullable<double> RepairableOrDamageDeliveryQuantity { get; set; }
        public Nullable<double> ReceivedByMRRQuantity { get; set; }
        public System.DateTime VendorRefChallanDate { get; set; }
        public string VendorDeliveryRouteNo { get; set; }
        public string VendorBillNo { get; set; }
        public Nullable<System.DateTime> VendorBillDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte Status { get; set; }
        public string PackageOrSpareParts { get; set; }
        public string RefDistribScheduleNo { get; set; }
    
        public virtual SHSDistributionPlan_RootWiseLocation SHSDistributionPlan_RootWiseLocation { get; set; }
    }
}
