//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ChallanDetails
    {
        public Inv_ChallanDetails()
        {
            this.Inv_ChallanDetailsWithSerialNo = new HashSet<Inv_ChallanDetailsWithSerialNo>();
            this.Inv_ChallanWithMultipleLocationsWithItemWiseDistribution = new HashSet<Inv_ChallanWithMultipleLocationsWithItemWiseDistribution>();
            this.Inv_MRRDetails = new HashSet<Inv_MRRDetails>();
            this.Inv_ItemTransactionDetails = new HashSet<Inv_ItemTransactionDetails>();
        }
    
        public string LocationCode { get; set; }
        public string ChallanSeqNo { get; set; }
        public byte CompSeqNo { get; set; }
        public string ItemCode { get; set; }
        public double DeliveryQuantity { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<byte> FromStoreLocation { get; set; }
        public Nullable<double> ReceivedByMRRQuantity { get; set; }
        public string RefItemTransType { get; set; }
        public string RefItemCategory { get; set; }
        public Nullable<byte> WarrantyInMonth { get; set; }
    
        public virtual Inv_ChallanMaster Inv_ChallanMaster { get; set; }
        public virtual ICollection<Inv_ChallanDetailsWithSerialNo> Inv_ChallanDetailsWithSerialNo { get; set; }
        public virtual ICollection<Inv_ChallanWithMultipleLocationsWithItemWiseDistribution> Inv_ChallanWithMultipleLocationsWithItemWiseDistribution { get; set; }
        public virtual ICollection<Inv_MRRDetails> Inv_MRRDetails { get; set; }
        public virtual ICollection<Inv_ItemTransactionDetails> Inv_ItemTransactionDetails { get; set; }
    }
}
