//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ChallanWithMultipleLocationsWithItemWiseDistribution
    {
        public string ChallanToLocationCode { get; set; }
        public string ChallanFromLocationCode { get; set; }
        public string ChallanSeqNo { get; set; }
        public byte CompSeqNo { get; set; }
        public string ItemCode { get; set; }
        public double DeliveryQuantity { get; set; }
    
        public virtual Inv_ChallanDetails Inv_ChallanDetails { get; set; }
        public virtual Inv_ChallanWithMultipleLocations Inv_ChallanWithMultipleLocations { get; set; }
    }
}
