//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class InvChallanOrMRRDetailsForItemLedger
    {
        public string TransType { get; set; }
        public string StoreLocation { get; set; }
        public System.DateTime TransDate { get; set; }
        public string FromOrToLocation { get; set; }
        public string RefDocNo { get; set; }
        public string DocSeqNo { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemCapacity { get; set; }
        public string ItemModel { get; set; }
        public double TransQuantity { get; set; }
        public string RefCustomerCode { get; set; }
        public string ItemTransTypeID { get; set; }
    }
}
