//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class LocationNEmployeeWiseDailySalesNCollectionTarget
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> Day01 { get; set; }
        public Nullable<int> Day02 { get; set; }
        public Nullable<int> Day03 { get; set; }
        public Nullable<int> Day04 { get; set; }
        public Nullable<int> Day05 { get; set; }
        public Nullable<int> Day06 { get; set; }
        public Nullable<int> Day07 { get; set; }
        public Nullable<int> Day08 { get; set; }
        public Nullable<int> Day09 { get; set; }
        public Nullable<int> Day10 { get; set; }
        public Nullable<int> Day11 { get; set; }
        public Nullable<int> Day12 { get; set; }
        public Nullable<int> Day13 { get; set; }
        public Nullable<int> Day14 { get; set; }
        public Nullable<int> Day15 { get; set; }
        public Nullable<int> Day16 { get; set; }
        public Nullable<int> Day17 { get; set; }
        public Nullable<int> Day18 { get; set; }
        public Nullable<int> Day19 { get; set; }
        public Nullable<int> Day20 { get; set; }
        public Nullable<int> Day21 { get; set; }
        public Nullable<int> Day22 { get; set; }
        public Nullable<int> Day23 { get; set; }
        public Nullable<int> Day24 { get; set; }
        public Nullable<int> Day25 { get; set; }
        public Nullable<int> Day26 { get; set; }
        public Nullable<int> Day27 { get; set; }
        public Nullable<int> Day28 { get; set; }
        public Nullable<int> Day29 { get; set; }
        public Nullable<int> Day30 { get; set; }
        public Nullable<int> TotalForTheMonth { get; set; }
    }
}
