//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class LocationAndEmployeeWiseWeeklySalesAndCollectionEntry
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public decimal WeeklyTarget { get; set; }
        public decimal WeeklyAchievement { get; set; }
        public Nullable<decimal> VarianceInAmount { get; set; }
        public Nullable<decimal> VarianceInPercentage { get; set; }
        public decimal CumulativeTarget { get; set; }
        public decimal CumulativeAchievement { get; set; }
        public Nullable<decimal> CumVarianceInAmount { get; set; }
        public Nullable<decimal> CumVarianceInPercentage { get; set; }
        public string Remarks { get; set; }
    }
}
