//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class MRRDetails
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public double ChallanQuantity { get; set; }
        public double RemainChallanQuantity { get; set; }
        public byte RefChallanCompSeqNo { get; set; }
        public string ModelID { get; set; }
        public string ItemModel { get; set; }
        public string CapacityID { get; set; }
        public string ItemCapacity { get; set; }
        public byte FromStoreLocation { get; set; }
        public string LocationCode { get; set; }
        public string ChallanToLocationCode { get; set; }
        public bool IsItASerializableItem { get; set; }
        public double AlreadyReceiveQuantity { get; set; }
    }
}
