//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class OverdueCollectionTargetVsAchievementByUnitOffice
    {
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public Nullable<decimal> WeeklyTarget { get; set; }
        public Nullable<decimal> WeeklyAchievement { get; set; }
        public Nullable<decimal> VarianceInAmount { get; set; }
        public Nullable<decimal> VarianceInPercentage { get; set; }
        public Nullable<decimal> CumulativeTarget { get; set; }
        public Nullable<decimal> CumulativeAchievement { get; set; }
        public Nullable<decimal> CumVarianceInAmount { get; set; }
        public Nullable<decimal> CumVarianceInPercentage { get; set; }
        public string Remarks { get; set; }
    }
}
