//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class RASolarMISEntities : DbContext
    {
        public RASolarMISEntities()
            : base("name=RASolarMISEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aud_AdjustmentReasonCodes> Aud_AdjustmentReasonCodes { get; set; }
        public DbSet<Aud_AuditAdjustmentObservationOnSalesAgreement> Aud_AuditAdjustmentObservationOnSalesAgreement { get; set; }
        public DbSet<Aud_AuditAdjustmentRelatedChallanOrMRRForReference> Aud_AuditAdjustmentRelatedChallanOrMRRForReference { get; set; }
        public DbSet<Aud_AuditAdjustmentRelatedCollectionFromCustomers> Aud_AuditAdjustmentRelatedCollectionFromCustomers { get; set; }
        public DbSet<Common_CashMemoBookMaster> Common_CashMemoBookMaster { get; set; }
        public DbSet<Common_CurrentYearMonthNWeek> Common_CurrentYearMonthNWeek { get; set; }
        public DbSet<Common_DistrictInfo> Common_DistrictInfo { get; set; }
        public DbSet<Common_LocationInfo> Common_LocationInfo { get; set; }
        public DbSet<Common_PeriodOpenClose> Common_PeriodOpenClose { get; set; }
        public DbSet<Common_ProgramInfo> Common_ProgramInfo { get; set; }
        public DbSet<Common_ProjectInfo> Common_ProjectInfo { get; set; }
        public DbSet<Common_RegionInfo> Common_RegionInfo { get; set; }
        public DbSet<Common_Sys_LocationType> Common_Sys_LocationType { get; set; }
        public DbSet<Common_Sys_StatusInfo> Common_Sys_StatusInfo { get; set; }
        public DbSet<Common_Sys_SystemSettings> Common_Sys_SystemSettings { get; set; }
        public DbSet<Common_UnionInfo> Common_UnionInfo { get; set; }
        public DbSet<Common_UpazillaInfo> Common_UpazillaInfo { get; set; }
        public DbSet<Common_ZoneInfo> Common_ZoneInfo { get; set; }
        public DbSet<Hrm_LocationWiseEmployee> Hrm_LocationWiseEmployee { get; set; }
        public DbSet<Inv_ChallanDetails> Inv_ChallanDetails { get; set; }
        public DbSet<Inv_ChallanDetailsWithSerialNo> Inv_ChallanDetailsWithSerialNo { get; set; }
        public DbSet<Inv_ChallanMaster> Inv_ChallanMaster { get; set; }
        public DbSet<Inv_ChallanWithMultipleLocations> Inv_ChallanWithMultipleLocations { get; set; }
        public DbSet<Inv_ChallanWithMultipleLocationsWithItemWiseDistribution> Inv_ChallanWithMultipleLocationsWithItemWiseDistribution { get; set; }
        public DbSet<Inv_ItemCategorySubCategory> Inv_ItemCategorySubCategory { get; set; }
        public DbSet<Inv_ItemMaster> Inv_ItemMaster { get; set; }
        public DbSet<Inv_ItemModel> Inv_ItemModel { get; set; }
        public DbSet<Inv_ItemStockByLocation> Inv_ItemStockByLocation { get; set; }
        public DbSet<Inv_ItemTransactionTypes> Inv_ItemTransactionTypes { get; set; }
        public DbSet<Inv_MRRDetails> Inv_MRRDetails { get; set; }
        public DbSet<Inv_MRRDetailsWithSerialNo> Inv_MRRDetailsWithSerialNo { get; set; }
        public DbSet<Inv_StoreLocation> Inv_StoreLocation { get; set; }
        public DbSet<Inv_Sys_ItemType> Inv_Sys_ItemType { get; set; }
        public DbSet<Sal_CollectionFromCustomers> Sal_CollectionFromCustomers { get; set; }
        public DbSet<Sal_CollectionTypeInfo> Sal_CollectionTypeInfo { get; set; }
        public DbSet<Sal_CustomerFuelUsed> Sal_CustomerFuelUsed { get; set; }
        public DbSet<Sal_CustomerIncomeRange> Sal_CustomerIncomeRange { get; set; }
        public DbSet<Sal_CustomerOccupations> Sal_CustomerOccupations { get; set; }
        public DbSet<Sal_CustomerRelations> Sal_CustomerRelations { get; set; }
        public DbSet<Sal_CustomerTrainingTransDetails> Sal_CustomerTrainingTransDetails { get; set; }
        public DbSet<Sal_CustomerType> Sal_CustomerType { get; set; }
        public DbSet<Sal_CustomerWiseOverdueBalanceForTracker> Sal_CustomerWiseOverdueBalanceForTracker { get; set; }
        public DbSet<Sal_ItemSetDetail> Sal_ItemSetDetail { get; set; }
        public DbSet<Sal_ItemSetMaster> Sal_ItemSetMaster { get; set; }
        public DbSet<Sal_Light> Sal_Light { get; set; }
        public DbSet<Sal_ListedUnitPriceForSparePartsSales> Sal_ListedUnitPriceForSparePartsSales { get; set; }
        public DbSet<Sal_LocationNEmployeeWiseActivityDaily> Sal_LocationNEmployeeWiseActivityDaily { get; set; }
        public DbSet<Sal_LocationNEmployeeWiseActivityMonthly> Sal_LocationNEmployeeWiseActivityMonthly { get; set; }
        public DbSet<Sal_LocationNEmployeeWiseDailySalesNCollectionTarget> Sal_LocationNEmployeeWiseDailySalesNCollectionTarget { get; set; }
        public DbSet<Sal_LocationWiseSalesNCollectionTarget> Sal_LocationWiseSalesNCollectionTarget { get; set; }
        public DbSet<Sal_ModeOfPayment> Sal_ModeOfPayment { get; set; }
        public DbSet<Sal_PackageDetail> Sal_PackageDetail { get; set; }
        public DbSet<Sal_PackageMaster> Sal_PackageMaster { get; set; }
        public DbSet<Sal_PackageOrItemCapacity> Sal_PackageOrItemCapacity { get; set; }
        public DbSet<Sal_SalesAgreementClosedWithFullPaidOrWaive> Sal_SalesAgreementClosedWithFullPaidOrWaive { get; set; }
        public DbSet<Sal_SalesItems> Sal_SalesItems { get; set; }
        public DbSet<Sal_SalesItemsWithSerialNo> Sal_SalesItemsWithSerialNo { get; set; }
        public DbSet<Sal_SparePartsSalesItems> Sal_SparePartsSalesItems { get; set; }
        public DbSet<Sal_SparePartsSalesItemsWithSerialNo> Sal_SparePartsSalesItemsWithSerialNo { get; set; }
        public DbSet<Sal_SystemReturn> Sal_SystemReturn { get; set; }
        public DbSet<Sal_SystemReturnItems> Sal_SystemReturnItems { get; set; }
        public DbSet<Sal_SystemReturnItemsWithSerialNo> Sal_SystemReturnItemsWithSerialNo { get; set; }
        public DbSet<Sal_TempApprovalForSalesAgreementClosed> Sal_TempApprovalForSalesAgreementClosed { get; set; }
        public DbSet<Sal_Validation_CapacityVsLight> Sal_Validation_CapacityVsLight { get; set; }
        public DbSet<Sal_Validation_CustomerTypeVsModeOfPayment> Sal_Validation_CustomerTypeVsModeOfPayment { get; set; }
        public DbSet<Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage> Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage { get; set; }
        public DbSet<Sal_Validation_ModeOfPaymentNPackageVsDiscount> Sal_Validation_ModeOfPaymentNPackageVsDiscount { get; set; }
        public DbSet<Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy> Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy { get; set; }
        public DbSet<Sal_Validation_ModeOfPaymentVsPackage> Sal_Validation_ModeOfPaymentVsPackage { get; set; }
        public DbSet<Sal_Validation_ModeOfPaymentWiseDiscountPolicy> Sal_Validation_ModeOfPaymentWiseDiscountPolicy { get; set; }
        public DbSet<Sal_Validation_UnitVsUpazilla> Sal_Validation_UnitVsUpazilla { get; set; }
        public DbSet<Sal_ODCustomerGrading> Sal_ODCustomerGrading { get; set; }
        public DbSet<Sal_ODRecoveryCommitmentByRMnZM> Sal_ODRecoveryCommitmentByRMnZM { get; set; }
        public DbSet<Sal_SalesAgreementPrePost> Sal_SalesAgreementPrePost { get; set; }
        public DbSet<Sal_SalesItemsWithSerialNoPrePost> Sal_SalesItemsWithSerialNoPrePost { get; set; }
        public DbSet<Sal_Validation_ProgramVsCustomerTypeNModeOfPayment> Sal_Validation_ProgramVsCustomerTypeNModeOfPayment { get; set; }
        public DbSet<Fix_EmployeeWiseFixedAssetsAllocation> Fix_EmployeeWiseFixedAssetsAllocation { get; set; }
        public DbSet<Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo> Fix_EmployeeWiseFixedAssetsAllocationWithSerialNo { get; set; }
        public DbSet<Inv_ItemTransactionDetails> Inv_ItemTransactionDetails { get; set; }
        public DbSet<Inv_ItemTransactionDetailsWithSerialNo> Inv_ItemTransactionDetailsWithSerialNo { get; set; }
        public DbSet<Sal_CustomerTrainingSchedule> Sal_CustomerTrainingSchedule { get; set; }
        public DbSet<Inv_MRRMaster> Inv_MRRMaster { get; set; }
        public DbSet<Sal_CollectionFromCustomersPrePost> Sal_CollectionFromCustomersPrePost { get; set; }
        public DbSet<Inv_ItemNItemCategoryWithSerialNoMaster> Inv_ItemNItemCategoryWithSerialNoMaster { get; set; }
        public DbSet<Inv_ItemStockWithSerialNoByLocation> Inv_ItemStockWithSerialNoByLocation { get; set; }
        public DbSet<Inv_Validation_SubstituteItemNMapping> Inv_Validation_SubstituteItemNMapping { get; set; }
        public DbSet<Inv_VendorInfo> Inv_VendorInfo { get; set; }
        public DbSet<SHSDistributionPlan_Master> SHSDistributionPlan_Master { get; set; }
        public DbSet<SHSDistributionPlan_IndividualItem> SHSDistributionPlan_IndividualItem { get; set; }
        public DbSet<Inv_RouteMaster> Inv_RouteMaster { get; set; }
        public DbSet<Inv_RouteDetail> Inv_RouteDetail { get; set; }
        public DbSet<Sal_SalesAgreement> Sal_SalesAgreement { get; set; }
        public DbSet<Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy> Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy { get; set; }
        public DbSet<Inv_ERPVersusPhysicalBalance> Inv_ERPVersusPhysicalBalance { get; set; }
        public DbSet<Inv_VendorChallanWithItemReferenceToCheck> Inv_VendorChallanWithItemReferenceToCheck { get; set; }
        public DbSet<Sal_DailyBusinessPerformanceMonitoring_SalesAndRecoveryStatusByUnit> Sal_DailyBusinessPerformanceMonitoring_SalesAndRecoveryStatusByUnit { get; set; }
        public DbSet<Common_UnitInfo> Common_UnitInfo { get; set; }
        public DbSet<SHSDistributionPlan_RootWiseLocation> SHSDistributionPlan_RootWiseLocation { get; set; }
        public DbSet<SHSDistributionPlan_RootWiseLocationNPackage> SHSDistributionPlan_RootWiseLocationNPackage { get; set; }
        public DbSet<Sal_SparePartsSalesMaster> Sal_SparePartsSalesMaster { get; set; }
        public DbSet<Sal_CustomerTrainingTransMaster> Sal_CustomerTrainingTransMaster { get; set; }
        public DbSet<Sal_SparePartsSales_DataFromExternalSources> Sal_SparePartsSales_DataFromExternalSources { get; set; }
        public DbSet<Sal_Customer> Sal_Customer { get; set; }
        public DbSet<Sal_CustomerPrePost> Sal_CustomerPrePost { get; set; }
        public DbSet<Sal_CustomerInfoBackup> Sal_CustomerInfoBackup { get; set; }
        public DbSet<Sal_SalesItemsPrePost> Sal_SalesItemsPrePost { get; set; }
        public DbSet<Sal_SalesAgreementPrePost_DataFromExternalSources> Sal_SalesAgreementPrePost_DataFromExternalSources { get; set; }
        public DbSet<Sal_CustomerStatus> Sal_CustomerStatus { get; set; }
    
        public virtual int AESAL_CustomerTrainingExpensesV2(string prmUnitCode, string prmTrainingDate, Nullable<byte> prmTrainingBatchNo, string prmUserID, string prmDBTransType)
        {
            var prmUnitCodeParameter = prmUnitCode != null ?
                new ObjectParameter("prmUnitCode", prmUnitCode) :
                new ObjectParameter("prmUnitCode", typeof(string));
    
            var prmTrainingDateParameter = prmTrainingDate != null ?
                new ObjectParameter("prmTrainingDate", prmTrainingDate) :
                new ObjectParameter("prmTrainingDate", typeof(string));
    
            var prmTrainingBatchNoParameter = prmTrainingBatchNo.HasValue ?
                new ObjectParameter("prmTrainingBatchNo", prmTrainingBatchNo) :
                new ObjectParameter("prmTrainingBatchNo", typeof(byte));
    
            var prmUserIDParameter = prmUserID != null ?
                new ObjectParameter("prmUserID", prmUserID) :
                new ObjectParameter("prmUserID", typeof(string));
    
            var prmDBTransTypeParameter = prmDBTransType != null ?
                new ObjectParameter("prmDBTransType", prmDBTransType) :
                new ObjectParameter("prmDBTransType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AESAL_CustomerTrainingExpensesV2", prmUnitCodeParameter, prmTrainingDateParameter, prmTrainingBatchNoParameter, prmUserIDParameter, prmDBTransTypeParameter);
        }
    
        public virtual int AESAL_SalesReturnV2(string prmCustomerCode, string prmDBTransType)
        {
            var prmCustomerCodeParameter = prmCustomerCode != null ?
                new ObjectParameter("prmCustomerCode", prmCustomerCode) :
                new ObjectParameter("prmCustomerCode", typeof(string));
    
            var prmDBTransTypeParameter = prmDBTransType != null ?
                new ObjectParameter("prmDBTransType", prmDBTransType) :
                new ObjectParameter("prmDBTransType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AESAL_SalesReturnV2", prmCustomerCodeParameter, prmDBTransTypeParameter);
        }
    
        public virtual int AESAL_SparePartsSalesV2(string prmLocationCode, string prmSPSSeqNo, string prmDBTransType)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmSPSSeqNoParameter = prmSPSSeqNo != null ?
                new ObjectParameter("prmSPSSeqNo", prmSPSSeqNo) :
                new ObjectParameter("prmSPSSeqNo", typeof(string));
    
            var prmDBTransTypeParameter = prmDBTransType != null ?
                new ObjectParameter("prmDBTransType", prmDBTransType) :
                new ObjectParameter("prmDBTransType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AESAL_SparePartsSalesV2", prmLocationCodeParameter, prmSPSSeqNoParameter, prmDBTransTypeParameter);
        }
    
        public virtual ObjectResult<ChallanInboxForChallanWithMRR> ChallanInboxForChallanWithMRR(string prmLocationCode, string prmItemType)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmItemTypeParameter = prmItemType != null ?
                new ObjectParameter("prmItemType", prmItemType) :
                new ObjectParameter("prmItemType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChallanInboxForChallanWithMRR>("ChallanInboxForChallanWithMRR", prmLocationCodeParameter, prmItemTypeParameter);
        }
    
        public virtual ObjectResult<ClosingInventoryValuation> ClosingInventoryValuation(string prmYearMonth)
        {
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClosingInventoryValuation>("ClosingInventoryValuation", prmYearMonthParameter);
        }
    
        public virtual ObjectResult<CollectionEfficiencyByCustomer> CollectionEfficiencyByCustomer(string prmYearMonth, string prmLocationCode)
        {
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CollectionEfficiencyByCustomer>("CollectionEfficiencyByCustomer", prmYearMonthParameter, prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<CollectionEfficiencyByUnitOfficeSummary> CollectionEfficiencyByUnitOfficeSummary(string prmYearMonth, string prmLocationCode, string prmReportType)
        {
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CollectionEfficiencyByUnitOfficeSummary>("CollectionEfficiencyByUnitOfficeSummary", prmYearMonthParameter, prmLocationCodeParameter, prmReportTypeParameter);
        }
    
        public virtual ObjectResult<CustomerInfoNPackageDetailsForSystemReturn> CustomerInfoNPackageDetailsForSystemReturn(string customerCode, Nullable<System.DateTime> returnDate)
        {
            var customerCodeParameter = customerCode != null ?
                new ObjectParameter("CustomerCode", customerCode) :
                new ObjectParameter("CustomerCode", typeof(string));
    
            var returnDateParameter = returnDate.HasValue ?
                new ObjectParameter("ReturnDate", returnDate) :
                new ObjectParameter("ReturnDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomerInfoNPackageDetailsForSystemReturn>("CustomerInfoNPackageDetailsForSystemReturn", customerCodeParameter, returnDateParameter);
        }
    
        public virtual ObjectResult<CustomerStatusListV2> CustomerStatusListV2(string prmUnit_Code, Nullable<byte> prmCustomerStatus, Nullable<System.DateTime> prmCurrentCollectedDate)
        {
            var prmUnit_CodeParameter = prmUnit_Code != null ?
                new ObjectParameter("prmUnit_Code", prmUnit_Code) :
                new ObjectParameter("prmUnit_Code", typeof(string));
    
            var prmCustomerStatusParameter = prmCustomerStatus.HasValue ?
                new ObjectParameter("prmCustomerStatus", prmCustomerStatus) :
                new ObjectParameter("prmCustomerStatus", typeof(byte));
    
            var prmCurrentCollectedDateParameter = prmCurrentCollectedDate.HasValue ?
                new ObjectParameter("prmCurrentCollectedDate", prmCurrentCollectedDate) :
                new ObjectParameter("prmCurrentCollectedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomerStatusListV2>("CustomerStatusListV2", prmUnit_CodeParameter, prmCustomerStatusParameter, prmCurrentCollectedDateParameter);
        }
    
        public virtual ObjectResult<CustomerTrainingDetails> CustomerTrainingDetails(string prmFromDate, string prmToDate)
        {
            var prmFromDateParameter = prmFromDate != null ?
                new ObjectParameter("prmFromDate", prmFromDate) :
                new ObjectParameter("prmFromDate", typeof(string));
    
            var prmToDateParameter = prmToDate != null ?
                new ObjectParameter("prmToDate", prmToDate) :
                new ObjectParameter("prmToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomerTrainingDetails>("CustomerTrainingDetails", prmFromDateParameter, prmToDateParameter);
        }
    
        public virtual ObjectResult<CustomerTrainingInfo> CustomerTrainingInfo(string unitCode, Nullable<bool> isCustomerTrained)
        {
            var unitCodeParameter = unitCode != null ?
                new ObjectParameter("UnitCode", unitCode) :
                new ObjectParameter("UnitCode", typeof(string));
    
            var isCustomerTrainedParameter = isCustomerTrained.HasValue ?
                new ObjectParameter("IsCustomerTrained", isCustomerTrained) :
                new ObjectParameter("IsCustomerTrained", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomerTrainingInfo>("CustomerTrainingInfo", unitCodeParameter, isCustomerTrainedParameter);
        }
    
        public virtual ObjectResult<CustomerTrainingSummary> CustomerTrainingSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomerTrainingSummary>("CustomerTrainingSummary", fromDateParameter, toDateParameter);
        }
    
        public virtual int CustomerTransferV2(string prmCustomerCode, string prmLocationCode, string prmCustomerTransferOrReceive, string prmTransferToUnit, string prmTransDate, string prmNoteForTransfer, string prmUserID, string prmDBTransType)
        {
            var prmCustomerCodeParameter = prmCustomerCode != null ?
                new ObjectParameter("prmCustomerCode", prmCustomerCode) :
                new ObjectParameter("prmCustomerCode", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmCustomerTransferOrReceiveParameter = prmCustomerTransferOrReceive != null ?
                new ObjectParameter("prmCustomerTransferOrReceive", prmCustomerTransferOrReceive) :
                new ObjectParameter("prmCustomerTransferOrReceive", typeof(string));
    
            var prmTransferToUnitParameter = prmTransferToUnit != null ?
                new ObjectParameter("prmTransferToUnit", prmTransferToUnit) :
                new ObjectParameter("prmTransferToUnit", typeof(string));
    
            var prmTransDateParameter = prmTransDate != null ?
                new ObjectParameter("prmTransDate", prmTransDate) :
                new ObjectParameter("prmTransDate", typeof(string));
    
            var prmNoteForTransferParameter = prmNoteForTransfer != null ?
                new ObjectParameter("prmNoteForTransfer", prmNoteForTransfer) :
                new ObjectParameter("prmNoteForTransfer", typeof(string));
    
            var prmUserIDParameter = prmUserID != null ?
                new ObjectParameter("prmUserID", prmUserID) :
                new ObjectParameter("prmUserID", typeof(string));
    
            var prmDBTransTypeParameter = prmDBTransType != null ?
                new ObjectParameter("prmDBTransType", prmDBTransType) :
                new ObjectParameter("prmDBTransType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CustomerTransferV2", prmCustomerCodeParameter, prmLocationCodeParameter, prmCustomerTransferOrReceiveParameter, prmTransferToUnitParameter, prmTransDateParameter, prmNoteForTransferParameter, prmUserIDParameter, prmDBTransTypeParameter);
        }
    
        public virtual ObjectResult<DayEndProcess> DayEndProcess(string prmLocationCode, string prmClosableDate, string prmDayOpenByUser)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmClosableDateParameter = prmClosableDate != null ?
                new ObjectParameter("prmClosableDate", prmClosableDate) :
                new ObjectParameter("prmClosableDate", typeof(string));
    
            var prmDayOpenByUserParameter = prmDayOpenByUser != null ?
                new ObjectParameter("prmDayOpenByUser", prmDayOpenByUser) :
                new ObjectParameter("prmDayOpenByUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DayEndProcess>("DayEndProcess", prmLocationCodeParameter, prmClosableDateParameter, prmDayOpenByUserParameter);
        }
    
        public virtual ObjectResult<DepretiatedPackagePriceBySRPanelSerial> DepretiatedPackagePriceBySRPanelSerial(string prmPanelSerialNo, string prmPackageCode)
        {
            var prmPanelSerialNoParameter = prmPanelSerialNo != null ?
                new ObjectParameter("prmPanelSerialNo", prmPanelSerialNo) :
                new ObjectParameter("prmPanelSerialNo", typeof(string));
    
            var prmPackageCodeParameter = prmPackageCode != null ?
                new ObjectParameter("prmPackageCode", prmPackageCode) :
                new ObjectParameter("prmPackageCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DepretiatedPackagePriceBySRPanelSerial>("DepretiatedPackagePriceBySRPanelSerial", prmPanelSerialNoParameter, prmPackageCodeParameter);
        }
    
        public virtual ObjectResult<GetCustomerFPRAndScheduledCollectionEntry> GetCustomerFPRAndScheduledCollectionEntry(string unitCode, string optionForMissingFPROrDay, string prmEmployeeID, Nullable<byte> prmScheduledCollectionDay)
        {
            var unitCodeParameter = unitCode != null ?
                new ObjectParameter("UnitCode", unitCode) :
                new ObjectParameter("UnitCode", typeof(string));
    
            var optionForMissingFPROrDayParameter = optionForMissingFPROrDay != null ?
                new ObjectParameter("OptionForMissingFPROrDay", optionForMissingFPROrDay) :
                new ObjectParameter("OptionForMissingFPROrDay", typeof(string));
    
            var prmEmployeeIDParameter = prmEmployeeID != null ?
                new ObjectParameter("prmEmployeeID", prmEmployeeID) :
                new ObjectParameter("prmEmployeeID", typeof(string));
    
            var prmScheduledCollectionDayParameter = prmScheduledCollectionDay.HasValue ?
                new ObjectParameter("prmScheduledCollectionDay", prmScheduledCollectionDay) :
                new ObjectParameter("prmScheduledCollectionDay", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerFPRAndScheduledCollectionEntry>("GetCustomerFPRAndScheduledCollectionEntry", unitCodeParameter, optionForMissingFPROrDayParameter, prmEmployeeIDParameter, prmScheduledCollectionDayParameter);
        }
    
        public virtual ObjectResult<GetCustomerTransferredButNotYetAccepted> GetCustomerTransferredButNotYetAccepted(string unitCode)
        {
            var unitCodeParameter = unitCode != null ?
                new ObjectParameter("UnitCode", unitCode) :
                new ObjectParameter("UnitCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerTransferredButNotYetAccepted>("GetCustomerTransferredButNotYetAccepted", unitCodeParameter);
        }
    
        public virtual ObjectResult<GetLocationNEmployeeWiseDailyEntry> GetLocationNEmployeeWiseDailyEntry(string prmLocationCode, string prmEmployeeID, string prmYearMonth, Nullable<System.DateTime> prmTransDate)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmEmployeeIDParameter = prmEmployeeID != null ?
                new ObjectParameter("prmEmployeeID", prmEmployeeID) :
                new ObjectParameter("prmEmployeeID", typeof(string));
    
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            var prmTransDateParameter = prmTransDate.HasValue ?
                new ObjectParameter("prmTransDate", prmTransDate) :
                new ObjectParameter("prmTransDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationNEmployeeWiseDailyEntry>("GetLocationNEmployeeWiseDailyEntry", prmLocationCodeParameter, prmEmployeeIDParameter, prmYearMonthParameter, prmTransDateParameter);
        }
    
        public virtual ObjectResult<GetLocationWiseEmployee> GetLocationWiseEmployee(string prmLocationCode)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationWiseEmployee>("GetLocationWiseEmployee", prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<GetLocationWiseEmployeeTarget> GetLocationWiseEmployeeTarget(string prmLocationCode)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationWiseEmployeeTarget>("GetLocationWiseEmployeeTarget", prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<GetUnitWiseCustomerTrainingSchedule> GetUnitWiseCustomerTrainingSchedule(string prmUnitCode, Nullable<System.DateTime> prmTrainingDate, Nullable<byte> prmTrainingBatchNo)
        {
            var prmUnitCodeParameter = prmUnitCode != null ?
                new ObjectParameter("prmUnitCode", prmUnitCode) :
                new ObjectParameter("prmUnitCode", typeof(string));
    
            var prmTrainingDateParameter = prmTrainingDate.HasValue ?
                new ObjectParameter("prmTrainingDate", prmTrainingDate) :
                new ObjectParameter("prmTrainingDate", typeof(System.DateTime));
    
            var prmTrainingBatchNoParameter = prmTrainingBatchNo.HasValue ?
                new ObjectParameter("prmTrainingBatchNo", prmTrainingBatchNo) :
                new ObjectParameter("prmTrainingBatchNo", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUnitWiseCustomerTrainingSchedule>("GetUnitWiseCustomerTrainingSchedule", prmUnitCodeParameter, prmTrainingDateParameter, prmTrainingBatchNoParameter);
        }
    
        public virtual ObjectResult<InvAvailableItemInALocation> InvAvailableItemInALocation(Nullable<byte> prmStoreLocation, string prmLocationCode, string prmItemCategory)
        {
            var prmStoreLocationParameter = prmStoreLocation.HasValue ?
                new ObjectParameter("prmStoreLocation", prmStoreLocation) :
                new ObjectParameter("prmStoreLocation", typeof(byte));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmItemCategoryParameter = prmItemCategory != null ?
                new ObjectParameter("prmItemCategory", prmItemCategory) :
                new ObjectParameter("prmItemCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InvAvailableItemInALocation>("InvAvailableItemInALocation", prmStoreLocationParameter, prmLocationCodeParameter, prmItemCategoryParameter);
        }
    
        public virtual ObjectResult<InvChallanOrMRRDetailsForItemLedger> InvChallanOrMRRDetailsForItemLedger(string prmLocationCode, string prmChallanOrMRRSeqNo, string prmChallanOrMRR)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmChallanOrMRRSeqNoParameter = prmChallanOrMRRSeqNo != null ?
                new ObjectParameter("prmChallanOrMRRSeqNo", prmChallanOrMRRSeqNo) :
                new ObjectParameter("prmChallanOrMRRSeqNo", typeof(string));
    
            var prmChallanOrMRRParameter = prmChallanOrMRR != null ?
                new ObjectParameter("prmChallanOrMRR", prmChallanOrMRR) :
                new ObjectParameter("prmChallanOrMRR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InvChallanOrMRRDetailsForItemLedger>("InvChallanOrMRRDetailsForItemLedger", prmLocationCodeParameter, prmChallanOrMRRSeqNoParameter, prmChallanOrMRRParameter);
        }
    
        public virtual ObjectResult<InventoryAtVendorValuationByStockLocation> InventoryAtVendorValuationByStockLocation(string prmYearMonth)
        {
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InventoryAtVendorValuationByStockLocation>("InventoryAtVendorValuationByStockLocation", prmYearMonthParameter);
        }
    
        public virtual ObjectResult<InventoryDataEntryStatus> InventoryDataEntryStatus(string prmReportType, string prmLocationCode, string prmYearMonth)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InventoryDataEntryStatus>("InventoryDataEntryStatus", prmReportTypeParameter, prmLocationCodeParameter, prmYearMonthParameter);
        }
    
        public virtual ObjectResult<InventorySummaryReportV2> InventorySummaryReportV2(string prmReportType, string prmItemType, Nullable<byte> prmStoreLocation, string prmLocationCode, string prmVendorID, Nullable<System.DateTime> prmFromDate, Nullable<System.DateTime> prmToDate)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmItemTypeParameter = prmItemType != null ?
                new ObjectParameter("prmItemType", prmItemType) :
                new ObjectParameter("prmItemType", typeof(string));
    
            var prmStoreLocationParameter = prmStoreLocation.HasValue ?
                new ObjectParameter("prmStoreLocation", prmStoreLocation) :
                new ObjectParameter("prmStoreLocation", typeof(byte));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmVendorIDParameter = prmVendorID != null ?
                new ObjectParameter("prmVendorID", prmVendorID) :
                new ObjectParameter("prmVendorID", typeof(string));
    
            var prmFromDateParameter = prmFromDate.HasValue ?
                new ObjectParameter("prmFromDate", prmFromDate) :
                new ObjectParameter("prmFromDate", typeof(System.DateTime));
    
            var prmToDateParameter = prmToDate.HasValue ?
                new ObjectParameter("prmToDate", prmToDate) :
                new ObjectParameter("prmToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InventorySummaryReportV2>("InventorySummaryReportV2", prmReportTypeParameter, prmItemTypeParameter, prmStoreLocationParameter, prmLocationCodeParameter, prmVendorIDParameter, prmFromDateParameter, prmToDateParameter);
        }
    
        public virtual ObjectResult<InventorySummaryToDetailViewReport> InventorySummaryToDetailViewReport(string prmYearMonth, string prmItemCode)
        {
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            var prmItemCodeParameter = prmItemCode != null ?
                new ObjectParameter("prmItemCode", prmItemCode) :
                new ObjectParameter("prmItemCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InventorySummaryToDetailViewReport>("InventorySummaryToDetailViewReport", prmYearMonthParameter, prmItemCodeParameter);
        }
    
        public virtual int InvGenerateItemTransactionForIssueInGeneral(string prmRefDocType, string prmLocationCode, string prmChallanSeqNo)
        {
            var prmRefDocTypeParameter = prmRefDocType != null ?
                new ObjectParameter("prmRefDocType", prmRefDocType) :
                new ObjectParameter("prmRefDocType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmChallanSeqNoParameter = prmChallanSeqNo != null ?
                new ObjectParameter("prmChallanSeqNo", prmChallanSeqNo) :
                new ObjectParameter("prmChallanSeqNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InvGenerateItemTransactionForIssueInGeneral", prmRefDocTypeParameter, prmLocationCodeParameter, prmChallanSeqNoParameter);
        }
    
        public virtual int InvGenerateItemTransactionForReceiveInGeneral(string prmRefDocType, string prmLocationCode, string prmMRRSeqNo)
        {
            var prmRefDocTypeParameter = prmRefDocType != null ?
                new ObjectParameter("prmRefDocType", prmRefDocType) :
                new ObjectParameter("prmRefDocType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmMRRSeqNoParameter = prmMRRSeqNo != null ?
                new ObjectParameter("prmMRRSeqNo", prmMRRSeqNo) :
                new ObjectParameter("prmMRRSeqNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InvGenerateItemTransactionForReceiveInGeneral", prmRefDocTypeParameter, prmLocationCodeParameter, prmMRRSeqNoParameter);
        }
    
        public virtual int InvGetAvailableItemInALocationWithAllocationToEmployee(Nullable<byte> prmStoreLocation, string prmLocationCode, string prmItemCategory, string prmEmployeeSelectionOption, string prmEmployeeID)
        {
            var prmStoreLocationParameter = prmStoreLocation.HasValue ?
                new ObjectParameter("prmStoreLocation", prmStoreLocation) :
                new ObjectParameter("prmStoreLocation", typeof(byte));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmItemCategoryParameter = prmItemCategory != null ?
                new ObjectParameter("prmItemCategory", prmItemCategory) :
                new ObjectParameter("prmItemCategory", typeof(string));
    
            var prmEmployeeSelectionOptionParameter = prmEmployeeSelectionOption != null ?
                new ObjectParameter("prmEmployeeSelectionOption", prmEmployeeSelectionOption) :
                new ObjectParameter("prmEmployeeSelectionOption", typeof(string));
    
            var prmEmployeeIDParameter = prmEmployeeID != null ?
                new ObjectParameter("prmEmployeeID", prmEmployeeID) :
                new ObjectParameter("prmEmployeeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InvGetAvailableItemInALocationWithAllocationToEmployee", prmStoreLocationParameter, prmLocationCodeParameter, prmItemCategoryParameter, prmEmployeeSelectionOptionParameter, prmEmployeeIDParameter);
        }
    
        public virtual ObjectResult<InvItemInTransit> InvItemInTransit(string prmOption, string prmItemType, string prmLocationCode, string prmItemCode, Nullable<System.DateTime> prmFromDate, Nullable<System.DateTime> prmToDate)
        {
            var prmOptionParameter = prmOption != null ?
                new ObjectParameter("prmOption", prmOption) :
                new ObjectParameter("prmOption", typeof(string));
    
            var prmItemTypeParameter = prmItemType != null ?
                new ObjectParameter("prmItemType", prmItemType) :
                new ObjectParameter("prmItemType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmItemCodeParameter = prmItemCode != null ?
                new ObjectParameter("prmItemCode", prmItemCode) :
                new ObjectParameter("prmItemCode", typeof(string));
    
            var prmFromDateParameter = prmFromDate.HasValue ?
                new ObjectParameter("prmFromDate", prmFromDate) :
                new ObjectParameter("prmFromDate", typeof(System.DateTime));
    
            var prmToDateParameter = prmToDate.HasValue ?
                new ObjectParameter("prmToDate", prmToDate) :
                new ObjectParameter("prmToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InvItemInTransit>("InvItemInTransit", prmOptionParameter, prmItemTypeParameter, prmLocationCodeParameter, prmItemCodeParameter, prmFromDateParameter, prmToDateParameter);
        }
    
        public virtual int InvUpdateStockPosition(string prmLocationCode)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InvUpdateStockPosition", prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<LocationAndEmployeeWiseWeeklySalesAndCollectionEntry> LocationAndEmployeeWiseWeeklySalesAndCollectionEntry(string prmLocationCode, string prmYearWeek)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmYearWeekParameter = prmYearWeek != null ?
                new ObjectParameter("prmYearWeek", prmYearWeek) :
                new ObjectParameter("prmYearWeek", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationAndEmployeeWiseWeeklySalesAndCollectionEntry>("LocationAndEmployeeWiseWeeklySalesAndCollectionEntry", prmLocationCodeParameter, prmYearWeekParameter);
        }
    
        public virtual ObjectResult<LocationNEmployeeWiseDailySalesNCollectionTarget> LocationNEmployeeWiseDailySalesNCollectionTarget(string prmLocationCode)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationNEmployeeWiseDailySalesNCollectionTarget>("LocationNEmployeeWiseDailySalesNCollectionTarget", prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<LocationWiseEmployeeTargetEntryCheck> LocationWiseEmployeeTargetEntryCheck(string prmLocationCode, string prmYearMonth)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocationWiseEmployeeTargetEntryCheck>("LocationWiseEmployeeTargetEntryCheck", prmLocationCodeParameter, prmYearMonthParameter);
        }
    
        public virtual ObjectResult<MRRDetails> MRRDetails(string challanLocationCode, string challanSequenceNumber, string mrrLocationCode)
        {
            var challanLocationCodeParameter = challanLocationCode != null ?
                new ObjectParameter("ChallanLocationCode", challanLocationCode) :
                new ObjectParameter("ChallanLocationCode", typeof(string));
    
            var challanSequenceNumberParameter = challanSequenceNumber != null ?
                new ObjectParameter("ChallanSequenceNumber", challanSequenceNumber) :
                new ObjectParameter("ChallanSequenceNumber", typeof(string));
    
            var mrrLocationCodeParameter = mrrLocationCode != null ?
                new ObjectParameter("MrrLocationCode", mrrLocationCode) :
                new ObjectParameter("MrrLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MRRDetails>("MRRDetails", challanLocationCodeParameter, challanSequenceNumberParameter, mrrLocationCodeParameter);
        }
    
        public virtual ObjectResult<OverdueCollectionTargetVsAchievementByUnitOffice> OverdueCollectionTargetVsAchievementByUnitOffice(string prmYearWeek)
        {
            var prmYearWeekParameter = prmYearWeek != null ?
                new ObjectParameter("prmYearWeek", prmYearWeek) :
                new ObjectParameter("prmYearWeek", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OverdueCollectionTargetVsAchievementByUnitOffice>("OverdueCollectionTargetVsAchievementByUnitOffice", prmYearWeekParameter);
        }
    
        public virtual ObjectResult<PackageDetails> PackageDetails(string packageCode, string modeOfPaymentID, string customerType)
        {
            var packageCodeParameter = packageCode != null ?
                new ObjectParameter("PackageCode", packageCode) :
                new ObjectParameter("PackageCode", typeof(string));
    
            var modeOfPaymentIDParameter = modeOfPaymentID != null ?
                new ObjectParameter("ModeOfPaymentID", modeOfPaymentID) :
                new ObjectParameter("ModeOfPaymentID", typeof(string));
    
            var customerTypeParameter = customerType != null ?
                new ObjectParameter("CustomerType", customerType) :
                new ObjectParameter("CustomerType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PackageDetails>("PackageDetails", packageCodeParameter, modeOfPaymentIDParameter, customerTypeParameter);
        }
    
        public virtual ObjectResult<PackageDetailsForSystemReturn> PackageDetailsForSystemReturn(string customerCode, Nullable<System.DateTime> returnDate)
        {
            var customerCodeParameter = customerCode != null ?
                new ObjectParameter("CustomerCode", customerCode) :
                new ObjectParameter("CustomerCode", typeof(string));
    
            var returnDateParameter = returnDate.HasValue ?
                new ObjectParameter("ReturnDate", returnDate) :
                new ObjectParameter("ReturnDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PackageDetailsForSystemReturn>("PackageDetailsForSystemReturn", customerCodeParameter, returnDateParameter);
        }
    
        public virtual ObjectResult<ProgressReview> ProgressReview()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProgressReview>("ProgressReview");
        }
    
        public virtual ObjectResult<ProgressReviewDataEntryStatusDaily> ProgressReviewDataEntryStatusDaily(string prmReportType, string prmLocationCode, string prmYearMonth, string prmRespectiveAreaUserID)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            var prmRespectiveAreaUserIDParameter = prmRespectiveAreaUserID != null ?
                new ObjectParameter("prmRespectiveAreaUserID", prmRespectiveAreaUserID) :
                new ObjectParameter("prmRespectiveAreaUserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProgressReviewDataEntryStatusDaily>("ProgressReviewDataEntryStatusDaily", prmReportTypeParameter, prmLocationCodeParameter, prmYearMonthParameter, prmRespectiveAreaUserIDParameter);
        }
    
        public virtual ObjectResult<REPSummaryForTheDayClosingForSales> REPSummaryForTheDayClosingForSales(string prmReportType, string prmLocationCode)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REPSummaryForTheDayClosingForSales>("REPSummaryForTheDayClosingForSales", prmReportTypeParameter, prmLocationCodeParameter);
        }
    
        public virtual int SalesAgreementSubmitV2(string prmCustomerCode, string prmDBTransType)
        {
            var prmCustomerCodeParameter = prmCustomerCode != null ?
                new ObjectParameter("prmCustomerCode", prmCustomerCode) :
                new ObjectParameter("prmCustomerCode", typeof(string));
    
            var prmDBTransTypeParameter = prmDBTransType != null ?
                new ObjectParameter("prmDBTransType", prmDBTransType) :
                new ObjectParameter("prmDBTransType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalesAgreementSubmitV2", prmCustomerCodeParameter, prmDBTransTypeParameter);
        }
    
        public virtual ObjectResult<SalesDataEntryStatus> SalesDataEntryStatus(string prmReportType, string prmLocationCode)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalesDataEntryStatus>("SalesDataEntryStatus", prmReportTypeParameter, prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<SalesSummaryToDetailView> SalesSummaryToDetailView(string prmYearMonth, string prmItemCode)
        {
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            var prmItemCodeParameter = prmItemCode != null ?
                new ObjectParameter("prmItemCode", prmItemCode) :
                new ObjectParameter("prmItemCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalesSummaryToDetailView>("SalesSummaryToDetailView", prmYearMonthParameter, prmItemCodeParameter);
        }
    
        public virtual ObjectResult<SalGetAvailableSerialNoForMRR> SalGetAvailableSerialNoForMRR(string prmRefDocType, string prmChallanLocationCode, string prmChallanSeqNo, string prmItemCode)
        {
            var prmRefDocTypeParameter = prmRefDocType != null ?
                new ObjectParameter("prmRefDocType", prmRefDocType) :
                new ObjectParameter("prmRefDocType", typeof(string));
    
            var prmChallanLocationCodeParameter = prmChallanLocationCode != null ?
                new ObjectParameter("prmChallanLocationCode", prmChallanLocationCode) :
                new ObjectParameter("prmChallanLocationCode", typeof(string));
    
            var prmChallanSeqNoParameter = prmChallanSeqNo != null ?
                new ObjectParameter("prmChallanSeqNo", prmChallanSeqNo) :
                new ObjectParameter("prmChallanSeqNo", typeof(string));
    
            var prmItemCodeParameter = prmItemCode != null ?
                new ObjectParameter("prmItemCode", prmItemCode) :
                new ObjectParameter("prmItemCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalGetAvailableSerialNoForMRR>("SalGetAvailableSerialNoForMRR", prmRefDocTypeParameter, prmChallanLocationCodeParameter, prmChallanSeqNoParameter, prmItemCodeParameter);
        }
    
        public virtual ObjectResult<SalSalesNCollectionTargetVsAchievementForGraph> SalSalesNCollectionTargetVsAchievementForGraph(string prmReportType, string prmLocationCode, string prmEmployeeID)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmEmployeeIDParameter = prmEmployeeID != null ?
                new ObjectParameter("prmEmployeeID", prmEmployeeID) :
                new ObjectParameter("prmEmployeeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalSalesNCollectionTargetVsAchievementForGraph>("SalSalesNCollectionTargetVsAchievementForGraph", prmReportTypeParameter, prmLocationCodeParameter, prmEmployeeIDParameter);
        }
    
        public virtual ObjectResult<SummarySheetForRegionalSalesPostingDetails> SalSummarySheetForRegionalSalesPostingDetails(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, string unitCode)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            var unitCodeParameter = unitCode != null ?
                new ObjectParameter("UnitCode", unitCode) :
                new ObjectParameter("UnitCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SummarySheetForRegionalSalesPostingDetails>("SalSummarySheetForRegionalSalesPostingDetails", dateFromParameter, dateToParameter, unitCodeParameter);
        }
    
        public virtual ObjectResult<SparePartSetDetils> SparePartSetDetils(string itemSetCode)
        {
            var itemSetCodeParameter = itemSetCode != null ?
                new ObjectParameter("ItemSetCode", itemSetCode) :
                new ObjectParameter("ItemSetCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SparePartSetDetils>("SparePartSetDetils", itemSetCodeParameter);
        }
    
        public virtual ObjectResult<SummaryForTheDayClosingForAccountingInfo> SummaryForTheDayClosingForAccountingInfo(string prmReportType, string prmLocationCode)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SummaryForTheDayClosingForAccountingInfo>("SummaryForTheDayClosingForAccountingInfo", prmReportTypeParameter, prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<SummaryForTheDayClosingForCollectionInfo> SummaryForTheDayClosingForCollectionInfo(string prmReportType, string prmLocationCode)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SummaryForTheDayClosingForCollectionInfo>("SummaryForTheDayClosingForCollectionInfo", prmReportTypeParameter, prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<SummaryForTheDayClosingForInventoryInfo> SummaryForTheDayClosingForInventoryInfo(string prmReportType, string prmLocationCode, Nullable<byte> prmStoreLocation)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmStoreLocationParameter = prmStoreLocation.HasValue ?
                new ObjectParameter("prmStoreLocation", prmStoreLocation) :
                new ObjectParameter("prmStoreLocation", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SummaryForTheDayClosingForInventoryInfo>("SummaryForTheDayClosingForInventoryInfo", prmReportTypeParameter, prmLocationCodeParameter, prmStoreLocationParameter);
        }
    
        public virtual ObjectResult<SummarySheetForRegionalSalesPosting> SummarySheetForRegionalSalesPosting(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, string regionCode)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            var regionCodeParameter = regionCode != null ?
                new ObjectParameter("RegionCode", regionCode) :
                new ObjectParameter("RegionCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SummarySheetForRegionalSalesPosting>("SummarySheetForRegionalSalesPosting", dateFromParameter, dateToParameter, regionCodeParameter);
        }
    
        public virtual ObjectResult<SystemReturnOrFullPaidCustomers> SystemReturnOrFullPaidCustomers(string prmYearMonth, string prmLocationCode, Nullable<byte> prmCustomerStatus)
        {
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmCustomerStatusParameter = prmCustomerStatus.HasValue ?
                new ObjectParameter("prmCustomerStatus", prmCustomerStatus) :
                new ObjectParameter("prmCustomerStatus", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SystemReturnOrFullPaidCustomers>("SystemReturnOrFullPaidCustomers", prmYearMonthParameter, prmLocationCodeParameter, prmCustomerStatusParameter);
        }
    
        public virtual ObjectResult<UnitCollectionVsHeadOfficePhysicalCashMovement> UnitCollectionVsHeadOfficePhysicalCashMovement(string prmReportType, string prmLocationCode, string prmYearMonth)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnitCollectionVsHeadOfficePhysicalCashMovement>("UnitCollectionVsHeadOfficePhysicalCashMovement", prmReportTypeParameter, prmLocationCodeParameter, prmYearMonthParameter);
        }
    
        public virtual ObjectResult<UnitWiseCustomerRegisterReport> UnitWiseCustomerRegisterReport(string unitCode)
        {
            var unitCodeParameter = unitCode != null ?
                new ObjectParameter("UnitCode", unitCode) :
                new ObjectParameter("UnitCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnitWiseCustomerRegisterReport>("UnitWiseCustomerRegisterReport", unitCodeParameter);
        }
    
        public virtual ObjectResult<WeeklySalesNCollectionStatus> WeeklySalesNCollectionStatus(string prmReportType, string prmLocationCode, string prmYearWeek)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            var prmYearWeekParameter = prmYearWeek != null ?
                new ObjectParameter("prmYearWeek", prmYearWeek) :
                new ObjectParameter("prmYearWeek", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WeeklySalesNCollectionStatus>("WeeklySalesNCollectionStatus", prmReportTypeParameter, prmLocationCodeParameter, prmYearWeekParameter);
        }
    
        public virtual ObjectResult<CustomerLedgerReport> CustomerLedgerReport(string prmCustomerCode)
        {
            var prmCustomerCodeParameter = prmCustomerCode != null ?
                new ObjectParameter("prmCustomerCode", prmCustomerCode) :
                new ObjectParameter("prmCustomerCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomerLedgerReport>("CustomerLedgerReport", prmCustomerCodeParameter);
        }
    
        public virtual ObjectResult<REP_GetEmployeeWiseSalesNColcTargetNAchievementForAUnit_Result> REP_GetEmployeeWiseSalesNColcTargetNAchievementForAUnit(string prmLocationCode)
        {
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REP_GetEmployeeWiseSalesNColcTargetNAchievementForAUnit_Result>("REP_GetEmployeeWiseSalesNColcTargetNAchievementForAUnit", prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<REP_DailyBusinessPerformanceMonitoring_DailyZonalPerformanceReport_Result> REP_DailyBusinessPerformanceMonitoring_DailyZonalPerformanceReport(string prmReportType)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<REP_DailyBusinessPerformanceMonitoring_DailyZonalPerformanceReport_Result>("REP_DailyBusinessPerformanceMonitoring_DailyZonalPerformanceReport", prmReportTypeParameter);
        }
    
        public virtual ObjectResult<DailyZonalPerformanceMonitoring> DailyZonalPerformanceMonitoring(string prmReportType)
        {
            var prmReportTypeParameter = prmReportType != null ?
                new ObjectParameter("prmReportType", prmReportType) :
                new ObjectParameter("prmReportType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DailyZonalPerformanceMonitoring>("DailyZonalPerformanceMonitoring", prmReportTypeParameter);
        }
    
        public virtual ObjectResult<SP_InvUpdateERPBalanceAndGetERPVersusPhysicalBalance_Result> SP_InvUpdateERPBalanceAndGetERPVersusPhysicalBalance(Nullable<byte> prmStoreLocation, string prmYearMonth, string prmLocationCode)
        {
            var prmStoreLocationParameter = prmStoreLocation.HasValue ?
                new ObjectParameter("prmStoreLocation", prmStoreLocation) :
                new ObjectParameter("prmStoreLocation", typeof(byte));
    
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_InvUpdateERPBalanceAndGetERPVersusPhysicalBalance_Result>("SP_InvUpdateERPBalanceAndGetERPVersusPhysicalBalance", prmStoreLocationParameter, prmYearMonthParameter, prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<InventoryERPVersusPhysicalBalance> InventoryERPVersusPhysicalBalance(Nullable<byte> prmStoreLocation, string prmYearMonth, string prmLocationCode)
        {
            var prmStoreLocationParameter = prmStoreLocation.HasValue ?
                new ObjectParameter("prmStoreLocation", prmStoreLocation) :
                new ObjectParameter("prmStoreLocation", typeof(byte));
    
            var prmYearMonthParameter = prmYearMonth != null ?
                new ObjectParameter("prmYearMonth", prmYearMonth) :
                new ObjectParameter("prmYearMonth", typeof(string));
    
            var prmLocationCodeParameter = prmLocationCode != null ?
                new ObjectParameter("prmLocationCode", prmLocationCode) :
                new ObjectParameter("prmLocationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InventoryERPVersusPhysicalBalance>("InventoryERPVersusPhysicalBalance", prmStoreLocationParameter, prmYearMonthParameter, prmLocationCodeParameter);
        }
    
        public virtual ObjectResult<SP_SalSparePartSetDetils_Result> SP_SalSparePartSetDetils(string itemSetCode)
        {
            var itemSetCodeParameter = itemSetCode != null ?
                new ObjectParameter("ItemSetCode", itemSetCode) :
                new ObjectParameter("ItemSetCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SalSparePartSetDetils_Result>("SP_SalSparePartSetDetils", itemSetCodeParameter);
        }
    
        public virtual ObjectResult<SP_PackageDetails_Result> SP_PackageDetails(string packageCode, string modeOfPaymentID, string customerType)
        {
            var packageCodeParameter = packageCode != null ?
                new ObjectParameter("PackageCode", packageCode) :
                new ObjectParameter("PackageCode", typeof(string));
    
            var modeOfPaymentIDParameter = modeOfPaymentID != null ?
                new ObjectParameter("ModeOfPaymentID", modeOfPaymentID) :
                new ObjectParameter("ModeOfPaymentID", typeof(string));
    
            var customerTypeParameter = customerType != null ?
                new ObjectParameter("CustomerType", customerType) :
                new ObjectParameter("CustomerType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PackageDetails_Result>("SP_PackageDetails", packageCodeParameter, modeOfPaymentIDParameter, customerTypeParameter);
        }
    
        public virtual ObjectResult<SP_PackageDetails1_Result> SP_PackageDetails1(string packageCode, string modeOfPaymentID, string customerType)
        {
            var packageCodeParameter = packageCode != null ?
                new ObjectParameter("PackageCode", packageCode) :
                new ObjectParameter("PackageCode", typeof(string));
    
            var modeOfPaymentIDParameter = modeOfPaymentID != null ?
                new ObjectParameter("ModeOfPaymentID", modeOfPaymentID) :
                new ObjectParameter("ModeOfPaymentID", typeof(string));
    
            var customerTypeParameter = customerType != null ?
                new ObjectParameter("CustomerType", customerType) :
                new ObjectParameter("CustomerType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PackageDetails1_Result>("SP_PackageDetails1", packageCodeParameter, modeOfPaymentIDParameter, customerTypeParameter);
        }
    }
}
