//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class REPSummaryForTheDayClosingForSales
    {
        public string Package { get; set; }
        public int NumberOfSalesUptoYesterday { get; set; }
        public int NumberOfSalesToday { get; set; }
        public int SalesTargetThisMonth { get; set; }
        public int SystemReturnThisMonth_Number { get; set; }
        public decimal SystemReturnThisMonth_Value { get; set; }
    }
}
