//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SalesAgreement
    {
        public Sal_SalesAgreement()
        {
            this.Aud_AuditAdjustmentObservationOnSalesAgreement = new HashSet<Aud_AuditAdjustmentObservationOnSalesAgreement>();
            this.Sal_CollectionFromCustomers = new HashSet<Sal_CollectionFromCustomers>();
            this.Sal_CollectionFromCustomersPrePost = new HashSet<Sal_CollectionFromCustomersPrePost>();
            this.Sal_SalesItems = new HashSet<Sal_SalesItems>();
        }
    
        public string CustomerCode { get; set; }
        public System.DateTime AgreementDate { get; set; }
        public string PackageCode { get; set; }
        public string ModeOfPaymentID { get; set; }
        public string CustomerType { get; set; }
        public byte NumberOfInstallment { get; set; }
        public decimal PackagePrice { get; set; }
        public string DiscountID { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal AmountAfterDiscount { get; set; }
        public string DownPaymentID { get; set; }
        public byte STDDownPaymentPercentage { get; set; }
        public decimal DownPaymentAmount { get; set; }
        public decimal TotalPrincipalReceivable { get; set; }
        public string ServiceChargeID { get; set; }
        public byte STDServiceChargePercentage { get; set; }
        public decimal TotalServiceChargeReceivable { get; set; }
        public decimal TotalPrincipalPlusServiceChargeReceivable { get; set; }
        public decimal InstallmentSize { get; set; }
        public decimal InstallmentSizePrincipal { get; set; }
        public decimal InstallmentSizeServiceCharge { get; set; }
        public Nullable<byte> ScheduledCollectionDay { get; set; }
        public string UnitCode { get; set; }
        public string ProjectCode { get; set; }
        public string ProgramCode { get; set; }
        public string CashMemoNo { get; set; }
        public string CashMemoUsesID { get; set; }
        public string RefMemoNo { get; set; }
        public string RefAELocationCode { get; set; }
        public Nullable<System.DateTime> RefAETransDate { get; set; }
        public string RefAEProjectCode { get; set; }
        public string RefAETransNo { get; set; }
        public decimal TechnicalFees { get; set; }
        public decimal Subsidies { get; set; }
        public byte DisbursementNo { get; set; }
        public string SalespersonCode { get; set; }
        public bool IsReSales { get; set; }
        public string PanelItemCode { get; set; }
        public string PanelSerialNo { get; set; }
        public string BatteryItemCode { get; set; }
        public string BatterySerialNo { get; set; }
        public string RefChallanLocationCode { get; set; }
        public string RefChallanSeqNo { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<Aud_AuditAdjustmentObservationOnSalesAgreement> Aud_AuditAdjustmentObservationOnSalesAgreement { get; set; }
        public virtual Inv_ItemNItemCategoryWithSerialNoMaster Inv_ItemNItemCategoryWithSerialNoMaster { get; set; }
        public virtual Inv_ItemNItemCategoryWithSerialNoMaster Inv_ItemNItemCategoryWithSerialNoMaster1 { get; set; }
        public virtual ICollection<Sal_CollectionFromCustomers> Sal_CollectionFromCustomers { get; set; }
        public virtual ICollection<Sal_CollectionFromCustomersPrePost> Sal_CollectionFromCustomersPrePost { get; set; }
        public virtual Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage { get; set; }
        public virtual Sal_Validation_ModeOfPaymentNPackageVsDiscount Sal_Validation_ModeOfPaymentNPackageVsDiscount { get; set; }
        public virtual Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy { get; set; }
        public virtual Sal_Validation_ProgramVsCustomerTypeNModeOfPayment Sal_Validation_ProgramVsCustomerTypeNModeOfPayment { get; set; }
        public virtual ICollection<Sal_SalesItems> Sal_SalesItems { get; set; }
        public virtual Sal_SystemReturn Sal_SystemReturn { get; set; }
        public virtual Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy { get; set; }
        public virtual Common_UnitInfo Common_UnitInfo { get; set; }
        public virtual Sal_Customer Sal_Customer { get; set; }
    }
}
