//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_PackageMaster
    {
        public Sal_PackageMaster()
        {
            this.Sal_PackageDetail = new HashSet<Sal_PackageDetail>();
            this.Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy = new HashSet<Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy>();
            this.Sal_Validation_ModeOfPaymentVsPackage = new HashSet<Sal_Validation_ModeOfPaymentVsPackage>();
        }
    
        public string PackageCode { get; set; }
        public string Description { get; set; }
        public string Capacity { get; set; }
        public string Light { get; set; }
        public string ProjectCode { get; set; }
        public decimal PerUnitSalesPrice { get; set; }
        public bool IsPriceChangeable { get; set; }
        public Nullable<decimal> MinSalesPrice { get; set; }
        public Nullable<decimal> MaxSalesPrice { get; set; }
        public string FixedModeOfPayment { get; set; }
        public bool IsValidFor_SalesWithNewPackagePrice { get; set; }
        public bool IsValidFor_ReSalesWithNewPackagePrice { get; set; }
        public bool IsValidFor_ReSalesWithDepretiatedPackagePrice { get; set; }
        public byte Status { get; set; }
        public Nullable<bool> IsValidForDistribution { get; set; }
        public decimal PerUnitSalesPriceForCashSales { get; set; }
    
        public virtual Sal_ModeOfPayment Sal_ModeOfPayment { get; set; }
        public virtual ICollection<Sal_PackageDetail> Sal_PackageDetail { get; set; }
        public virtual Sal_Validation_CapacityVsLight Sal_Validation_CapacityVsLight { get; set; }
        public virtual Sal_PackageOrItemCapacity Sal_PackageOrItemCapacity { get; set; }
        public virtual ICollection<Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy> Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy { get; set; }
        public virtual ICollection<Sal_Validation_ModeOfPaymentVsPackage> Sal_Validation_ModeOfPaymentVsPackage { get; set; }
    }
}
