//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SystemReturn
    {
        public Sal_SystemReturn()
        {
            this.Sal_SystemReturnItems = new HashSet<Sal_SystemReturnItems>();
        }
    
        public string CustomerCode { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public byte MonthUsage { get; set; }
        public decimal UsageChargeReceivable { get; set; }
        public decimal ServiceChargeReceivable { get; set; }
        public decimal NonReturnedItemValue { get; set; }
        public decimal TotalReceivable { get; set; }
        public decimal TotalRecovered_DPPlusInstallment { get; set; }
        public decimal ReceivableOrPayableAmount { get; set; }
        public Nullable<bool> IsPaidToCustomerOnApprovalByManagementWhenReceivable { get; set; }
        public decimal ActualReceivedOrPaidAmount { get; set; }
        public Nullable<decimal> DepretiatedPackagePrice { get; set; }
        public string PanelSerialNo { get; set; }
        public string BatterySerialNo { get; set; }
        public string RefAEUnitCode { get; set; }
        public Nullable<System.DateTime> RefAETransDate { get; set; }
        public string RefAEProjectCode { get; set; }
        public string RefAETransNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ApprovedByRM { get; set; }
        public Nullable<System.DateTime> ApprovedByRMDate { get; set; }
        public string ApprovedByZM { get; set; }
        public Nullable<System.DateTime> ApprovedByZMDate { get; set; }
        public string ApprovedByHO { get; set; }
        public Nullable<System.DateTime> ApprovedByHODate { get; set; }
    
        public virtual ICollection<Sal_SystemReturnItems> Sal_SystemReturnItems { get; set; }
        public virtual Sal_SalesAgreement Sal_SalesAgreement { get; set; }
    }
}
