//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_LocationNEmployeeWiseActivityDaily
    {
        public string LocationCode { get; set; }
        public string YearMonth { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> SalesAchievementToday { get; set; }
        public Nullable<decimal> RegColcAchievementToday { get; set; }
        public Nullable<decimal> OverdueColcAchievementToday { get; set; }
        public Nullable<bool> SystemInstallationToday { get; set; }
        public Nullable<bool> InstallmentCollectionToday { get; set; }
        public Nullable<bool> CustomerVisitForMarketingToday { get; set; }
        public Nullable<bool> MaintenanceServicingToday { get; set; }
        public Nullable<bool> BankOperationToday { get; set; }
        public Nullable<bool> OfficialVisitToOtherUnitToday { get; set; }
        public Nullable<bool> MeetingToday { get; set; }
        public Nullable<decimal> TAToday { get; set; }
        public string ReasonForTAToday { get; set; }
        public Nullable<bool> WasInLeaveToday { get; set; }
        public Nullable<bool> DeskWorksToday { get; set; }
        public Nullable<int> SystemReturnToday { get; set; }
        public Nullable<int> SystemReSaleToday { get; set; }
        public Nullable<int> CustomerTrainingToday { get; set; }
        public Nullable<int> BioGasSalesToday { get; set; }
        public Nullable<int> RSFBatterySalesToday { get; set; }
        public string RemarksToday { get; set; }
        public Nullable<bool> DataEntryInERPToday { get; set; }
        public Nullable<bool> SystemInstallationTomorrow { get; set; }
        public Nullable<bool> InstallmentCollectionTomorrow { get; set; }
        public Nullable<bool> CustomerVisitForMarketingTomorrow { get; set; }
        public Nullable<bool> MaintenanceServicingTomorrow { get; set; }
        public Nullable<bool> BankOperationTomorrow { get; set; }
        public Nullable<bool> OfficialVisitToOtherUnitTomorrow { get; set; }
        public Nullable<bool> MeetingTomorrow { get; set; }
        public Nullable<decimal> TATomorrow { get; set; }
        public string ReasonForTATomorrow { get; set; }
        public Nullable<bool> WillBeInLeaveTomorrow { get; set; }
        public Nullable<bool> DeskWorksTomorrow { get; set; }
        public Nullable<int> SystemReturnTomorrow { get; set; }
        public Nullable<int> SystemReSaleTomorrow { get; set; }
        public Nullable<int> CustomerTrainingTomorrow { get; set; }
        public Nullable<int> BioGasSalesTomorrow { get; set; }
        public Nullable<int> RSFBatterySalesTomorrow { get; set; }
        public string RemarksTomorrow { get; set; }
        public Nullable<bool> DataEntryInERPTomorrow { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<System.DateTime> DateOfTADA { get; set; }
        public Nullable<decimal> DAToday { get; set; }
        public string ReasonForDAToday { get; set; }
        public Nullable<byte> DaysOfPendingEntry { get; set; }
    
        public virtual Sal_LocationNEmployeeWiseDailySalesNCollectionTarget Sal_LocationNEmployeeWiseDailySalesNCollectionTarget { get; set; }
    }
}
