//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy
    {
        public Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy()
        {
            this.Aud_AuditAdjustmentObservationOnSalesAgreement = new HashSet<Aud_AuditAdjustmentObservationOnSalesAgreement>();
            this.Sal_SalesAgreement = new HashSet<Sal_SalesAgreement>();
            this.Sal_SalesAgreementPrePost = new HashSet<Sal_SalesAgreementPrePost>();
            this.Sal_SalesAgreementPrePost_DataFromExternalSources = new HashSet<Sal_SalesAgreementPrePost_DataFromExternalSources>();
        }
    
        public string ProgramCode { get; set; }
        public string CustomerType { get; set; }
        public string ModeOfPaymentID { get; set; }
        public string ServiceChargeID { get; set; }
        public string Description { get; set; }
        public byte ServiceChargePercentage { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Aud_AuditAdjustmentObservationOnSalesAgreement> Aud_AuditAdjustmentObservationOnSalesAgreement { get; set; }
        public virtual ICollection<Sal_SalesAgreement> Sal_SalesAgreement { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost> Sal_SalesAgreementPrePost { get; set; }
        public virtual Sal_Validation_ProgramVsCustomerTypeNModeOfPayment Sal_Validation_ProgramVsCustomerTypeNModeOfPayment { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost_DataFromExternalSources> Sal_SalesAgreementPrePost_DataFromExternalSources { get; set; }
    }
}
