//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_CollectionFromCustomers
    {
        public string CustomerCode { get; set; }
        public string YearMonth { get; set; }
        public byte SerialNo { get; set; }
        public string CollectionType { get; set; }
        public decimal CollectionAmount { get; set; }
        public Nullable<decimal> AdvanceAdjustmentAmount { get; set; }
        public Nullable<decimal> CollectionAmount_ServiceCharge { get; set; }
        public Nullable<decimal> CollectionAmount_Principal { get; set; }
        public Nullable<decimal> CollectionAmount_Advance { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public string CashMemoNo { get; set; }
        public string CashMemoUsesID { get; set; }
        public string RefMemoNo { get; set; }
        public string UserID { get; set; }
        public System.DateTime EntryTime { get; set; }
        public string CollectionInUnit { get; set; }
        public string CollectedByEmployee { get; set; }
        public string RefAELocationCode { get; set; }
        public Nullable<System.DateTime> RefAETransDate { get; set; }
        public string RefAEProjectCode { get; set; }
        public string RefAETransNo { get; set; }
        public string RefCashMemoAssignedToEmployee { get; set; }
        public string RefEmployeeAsCustomerFPR { get; set; }
    
        public virtual Aud_AuditAdjustmentRelatedCollectionFromCustomers Aud_AuditAdjustmentRelatedCollectionFromCustomers { get; set; }
        public virtual Sal_CollectionTypeInfo Sal_CollectionTypeInfo { get; set; }
        public virtual Sal_SalesAgreement Sal_SalesAgreement { get; set; }
    }
}
