//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_TempApprovalForSalesAgreementClosed
    {
        public string CustomerCode { get; set; }
        public string ApprovalNo { get; set; }
        public System.DateTime RequestedAgreementClosedDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<decimal> RemainingServiceChargeReceivableBeforeAdjustmentFromAdvance { get; set; }
        public Nullable<decimal> RemainingPrincipalReceivableBeforeAdjustmentFromAdvance { get; set; }
        public Nullable<decimal> AdvanceBalanceBeforeAdjustment { get; set; }
        public Nullable<decimal> RemainingServiceChargeReceivableAfterAdjustmentFromAdvance { get; set; }
        public Nullable<decimal> RemainingPrincipalReceivableAfterAdjustmentFromAdvance { get; set; }
        public Nullable<decimal> AdvanceBalanceAfterAdjustment { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string RequestedFromLocationCode { get; set; }
        public byte Status { get; set; }
    }
}
