//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Validation_ModeOfPaymentVsPackage
    {
        public Sal_Validation_ModeOfPaymentVsPackage()
        {
            this.Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage = new HashSet<Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage>();
            this.Sal_Validation_ModeOfPaymentNPackageVsDiscount = new HashSet<Sal_Validation_ModeOfPaymentNPackageVsDiscount>();
            this.Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy = new HashSet<Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy>();
        }
    
        public string ModeOfPaymentID { get; set; }
        public string PackageCode { get; set; }
        public byte Status { get; set; }
        public decimal PerUnitSalesPrice { get; set; }
    
        public virtual Sal_ModeOfPayment Sal_ModeOfPayment { get; set; }
        public virtual Sal_PackageMaster Sal_PackageMaster { get; set; }
        public virtual ICollection<Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage> Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage { get; set; }
        public virtual ICollection<Sal_Validation_ModeOfPaymentNPackageVsDiscount> Sal_Validation_ModeOfPaymentNPackageVsDiscount { get; set; }
        public virtual ICollection<Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy> Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy { get; set; }
    }
}
