//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_LocationWiseSalesNCollectionTarget
    {
        public Sal_LocationWiseSalesNCollectionTarget()
        {
            this.Sal_LocationNEmployeeWiseActivityMonthly = new HashSet<Sal_LocationNEmployeeWiseActivityMonthly>();
            this.Sal_LocationNEmployeeWiseDailySalesNCollectionTarget = new HashSet<Sal_LocationNEmployeeWiseDailySalesNCollectionTarget>();
        }
    
        public string LocationCode { get; set; }
        public string YearMonth { get; set; }
        public int SalesTarget { get; set; }
        public decimal RegularCollectionTarget { get; set; }
        public decimal OverdueCollectionTarget { get; set; }
        public bool IsEmployeeWiseTargetSettingCompleted { get; set; }
        public byte Status { get; set; }
        public string UserID { get; set; }
        public System.DateTime EntryTime { get; set; }
    
        public virtual ICollection<Sal_LocationNEmployeeWiseActivityMonthly> Sal_LocationNEmployeeWiseActivityMonthly { get; set; }
        public virtual ICollection<Sal_LocationNEmployeeWiseDailySalesNCollectionTarget> Sal_LocationNEmployeeWiseDailySalesNCollectionTarget { get; set; }
    }
}
