//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Validation_ModeOfPaymentNPackageVsDiscount
    {
        public Sal_Validation_ModeOfPaymentNPackageVsDiscount()
        {
            this.Sal_SalesAgreementPrePost = new HashSet<Sal_SalesAgreementPrePost>();
            this.Sal_SalesAgreement = new HashSet<Sal_SalesAgreement>();
            this.Sal_SalesAgreementPrePost_DataFromExternalSources = new HashSet<Sal_SalesAgreementPrePost_DataFromExternalSources>();
        }
    
        public string ModeOfPaymentID { get; set; }
        public string PackageCode { get; set; }
        public string DiscountID { get; set; }
        public byte Status { get; set; }
    
        public virtual Sal_Validation_ModeOfPaymentVsPackage Sal_Validation_ModeOfPaymentVsPackage { get; set; }
        public virtual Sal_Validation_ModeOfPaymentWiseDiscountPolicy Sal_Validation_ModeOfPaymentWiseDiscountPolicy { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost> Sal_SalesAgreementPrePost { get; set; }
        public virtual ICollection<Sal_SalesAgreement> Sal_SalesAgreement { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost_DataFromExternalSources> Sal_SalesAgreementPrePost_DataFromExternalSources { get; set; }
    }
}
