//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_CustomerStatus
    {
        public Sal_CustomerStatus()
        {
            this.Sal_CustomerTrainingTransDetails = new HashSet<Sal_CustomerTrainingTransDetails>();
        }
    
        public string CustomerCode { get; set; }
        public Nullable<bool> IsCustomerTrained { get; set; }
        public Nullable<System.DateTime> CustomerTrainingDate { get; set; }
        public string EmployeeAsFPR { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public Nullable<decimal> TotalPrincipalReceivableAsPerAgreement { get; set; }
        public Nullable<decimal> TotalServiceChargeReceivableAsPerAgreement { get; set; }
        public Nullable<System.DateTime> UpToDate { get; set; }
        public Nullable<byte> DueNoOfInstlmentUpToDateForAdvanceCalculation { get; set; }
        public Nullable<byte> DueNoOfInstlmentUpToDateForOverdueCalculation { get; set; }
        public Nullable<decimal> TotalServiceChargeReceivableConsideringDueNoOfInstallmentUpToDate { get; set; }
        public Nullable<decimal> TotalPrincipalWithoutDPReceivableConsideringDueNoOfInstallmentUpToDate { get; set; }
        public Nullable<decimal> TotalServiceChargeRecoveredUpToDate { get; set; }
        public Nullable<decimal> TotalPrincipalWithoutDPRecoveredUpToDate { get; set; }
        public Nullable<decimal> TotalAdvanceReceivedUpToDate { get; set; }
        public Nullable<decimal> TotalPrincipalWithoutDPPlusServiceChargePlusAdvanceReceivedUpToDate { get; set; }
        public Nullable<decimal> RemainingServiceChargeReceivableConsideringDueNoOfInstallmentUpToDate { get; set; }
        public Nullable<decimal> RemainingServiceChargeReceivableUpToDate { get; set; }
        public Nullable<decimal> RemainingPrincipalReceivableUpToDate { get; set; }
        public Nullable<decimal> OverdueServiceChargeUpToDate { get; set; }
        public Nullable<decimal> OverduePrincipalUpToDate { get; set; }
        public Nullable<decimal> OverdueOrAdvanceBalanceUpToDate { get; set; }
        public Nullable<decimal> OutstandingBalanceUpToDate { get; set; }
        public Nullable<decimal> AE_TotalCollectionInCashAmountUpToDate { get; set; }
        public Nullable<decimal> AE_TotalCollectionFromAdvanceAdjustmentUpToDate { get; set; }
        public Nullable<decimal> AE_TotalServiceChargeRecoveredAmountUpToDate { get; set; }
        public Nullable<decimal> AE_TotalPrincipalRecoveredAmountUpToDate { get; set; }
        public Nullable<decimal> AE_TotalAdvanceCollectionAmountUpToDate { get; set; }
        public Nullable<System.DateTime> RefreshOnForUpToDate { get; set; }
        public Nullable<System.DateTime> LastDateOfLastClosedMonth { get; set; }
        public Nullable<byte> NoOfMonthPassedAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<byte> DueNoOfInstllmentAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> TotalServiceChargeReceivableConsideringDueNoOfInstallmentAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> TotalPrincipalWithoutDPReceivableConsideringDueNoOfInstallmentAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> TotalServiceChargeRecoveredAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> TotalPrincipalWithoutDPRecoveredAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> TotalAdvanceReceivedAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> TotalPrincipalWithoutDPPlusServiceChargePlusAdvanceReceivedAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> RemainingServiceChargeReceivableConsideringDueNoOfInstallmentAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> RemainingServiceChargeReceivableAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> RemainingPrincipalReceivableAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> OverdueServiceChargeAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> OverduePrincipalAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> OverdueOrAdvanceBalanceAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<decimal> OutstandingBalanceAtTheEndOfLastClosedMonth { get; set; }
        public Nullable<System.DateTime> RefreshOnForTheEndOfLastClosedMonth { get; set; }
        public string CustomerCategory { get; set; }
        public string CriticalCustomerCategoryID { get; set; }
        public string ActionForSettlementID { get; set; }
        public Nullable<bool> IsCustomerPoliticallyInfluential { get; set; }
        public Nullable<bool> IsCustomerALocalMuscleMan { get; set; }
        public Nullable<bool> IsCustomerNotWillingToPay { get; set; }
        public Nullable<bool> IsPrincipalAdjustedInAdvanceBeforeDueForClosingWithFullPaidOrWaive { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<byte> ClosedByStatus { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> GeoLocationID { get; set; }
        public string PanelSerialNoAtHome { get; set; }
        public string BatterySerialNoAtHome { get; set; }
        public string CustomerMobileNo { get; set; }
    
        public virtual Sal_Customer Sal_Customer { get; set; }
        public virtual ICollection<Sal_CustomerTrainingTransDetails> Sal_CustomerTrainingTransDetails { get; set; }
    }
}
