//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_DailyBusinessPerformanceMonitoring_SalesAndRecoveryStatusByUnit
    {
        public string YearMonth { get; set; }
        public string LocationCode { get; set; }
        public string UMLastOverallRemarks { get; set; }
        public System.DateTime UMLastOverallRemarksEntryDate { get; set; }
        public string AMLastRemarks { get; set; }
        public Nullable<System.DateTime> AMLastRemarksEntryDate { get; set; }
    }
}
