//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Validation_ProgramVsCustomerTypeNModeOfPayment
    {
        public Sal_Validation_ProgramVsCustomerTypeNModeOfPayment()
        {
            this.Sal_SalesAgreement = new HashSet<Sal_SalesAgreement>();
            this.Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy = new HashSet<Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy>();
        }
    
        public string ProgramCode { get; set; }
        public string CustomerType { get; set; }
        public string ModeOfPaymentID { get; set; }
        public byte Status { get; set; }
    
        public virtual Common_ProgramInfo Common_ProgramInfo { get; set; }
        public virtual Sal_Validation_CustomerTypeVsModeOfPayment Sal_Validation_CustomerTypeVsModeOfPayment { get; set; }
        public virtual ICollection<Sal_SalesAgreement> Sal_SalesAgreement { get; set; }
        public virtual ICollection<Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy> Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy { get; set; }
    }
}
