//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_CustomerTrainingTransMaster
    {
        public Sal_CustomerTrainingTransMaster()
        {
            this.Sal_CustomerTrainingTransDetails = new HashSet<Sal_CustomerTrainingTransDetails>();
        }
    
        public string UnitCode { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public byte TrainingBatchNo { get; set; }
        public System.DateTime RefScheduledDate { get; set; }
        public byte RefScheduledBatchNo { get; set; }
        public byte NoOfParticipantAttend { get; set; }
        public decimal TotalTrainingAllowance { get; set; }
        public decimal TotalEntertainmentExp { get; set; }
        public string TrainerEmployeeID { get; set; }
        public string RefAELocationCode { get; set; }
        public Nullable<System.DateTime> RefAETransDate { get; set; }
        public string RefAEProjectCode { get; set; }
        public string RefAETransNo { get; set; }
        public Nullable<decimal> RefIDCOLTrainingNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte Status { get; set; }
    
        public virtual Common_UnitInfo Common_UnitInfo { get; set; }
        public virtual Sal_CustomerTrainingSchedule Sal_CustomerTrainingSchedule { get; set; }
        public virtual ICollection<Sal_CustomerTrainingTransDetails> Sal_CustomerTrainingTransDetails { get; set; }
    }
}
