//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SystemReturnItems
    {
        public Sal_SystemReturnItems()
        {
            this.Sal_SystemReturnItemsWithSerialNo = new HashSet<Sal_SystemReturnItemsWithSerialNo>();
        }
    
        public string CustomerCode { get; set; }
        public byte CompSeqNo { get; set; }
        public string ItemCode { get; set; }
        public double SoldQuantity { get; set; }
        public double ReturnQuantity { get; set; }
        public byte ReturnInToStoreLocation { get; set; }
        public decimal UnitCost { get; set; }
        public decimal NonReturnItemsValue { get; set; }
    
        public virtual Sal_SystemReturn Sal_SystemReturn { get; set; }
        public virtual ICollection<Sal_SystemReturnItemsWithSerialNo> Sal_SystemReturnItemsWithSerialNo { get; set; }
    }
}
