//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_CollectionTypeInfo
    {
        public Sal_CollectionTypeInfo()
        {
            this.Sal_CollectionFromCustomers = new HashSet<Sal_CollectionFromCustomers>();
            this.Sal_CollectionFromCustomersPrePost = new HashSet<Sal_CollectionFromCustomersPrePost>();
        }
    
        public string CollectionTypeID { get; set; }
        public string CollectionTypeDesc { get; set; }
    
        public virtual ICollection<Sal_CollectionFromCustomers> Sal_CollectionFromCustomers { get; set; }
        public virtual ICollection<Sal_CollectionFromCustomersPrePost> Sal_CollectionFromCustomersPrePost { get; set; }
    }
}
