//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SparePartsSalesMaster
    {
        public Sal_SparePartsSalesMaster()
        {
            this.Sal_SparePartsSalesItems = new HashSet<Sal_SparePartsSalesItems>();
        }
    
        public string LocationCode { get; set; }
        public string SPSSeqNo { get; set; }
        public System.DateTime SPSDate { get; set; }
        public string ProjectCode { get; set; }
        public string ProgramCode { get; set; }
        public string ItemSetCode { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal SalesAmountAfterDiscount { get; set; }
        public string CashMemoNo { get; set; }
        public string CashMemoUsesID { get; set; }
        public string RefMemoNo { get; set; }
        public string RefCustomerCode { get; set; }
        public byte FromStoreLocation { get; set; }
        public string ChallanLocationCode { get; set; }
        public string ChallanSeqNo { get; set; }
        public string ItemTransTypeID { get; set; }
        public string SalespersonCode { get; set; }
        public string RefAELocationCode { get; set; }
        public Nullable<System.DateTime> RefAETransDate { get; set; }
        public string RefAEProjectCode { get; set; }
        public string RefAETransNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte Status { get; set; }
    
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
        public virtual Inv_ChallanMaster Inv_ChallanMaster { get; set; }
        public virtual Sal_ItemSetMaster Sal_ItemSetMaster { get; set; }
        public virtual ICollection<Sal_SparePartsSalesItems> Sal_SparePartsSalesItems { get; set; }
    }
}
