//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_LocationNEmployeeWiseActivityMonthly
    {
        public string LocationCode { get; set; }
        public string EmployeeID { get; set; }
        public string YearMonth { get; set; }
        public Nullable<int> SalesCurrentMonthTarget { get; set; }
        public Nullable<int> SalesAchievementUptoLastDay { get; set; }
        public Nullable<double> SalesAchievementStatus { get; set; }
        public Nullable<int> RegColcCurrentMonthTarget { get; set; }
        public Nullable<int> RegColcAchievementUptoLastDay { get; set; }
        public Nullable<double> RegColcAchievementStatus { get; set; }
        public Nullable<int> OverdueColcCurrentMonthTarget { get; set; }
        public Nullable<int> OverdueColcAchievementUptoLastDay { get; set; }
        public Nullable<double> OverdueColcAchievementStatus { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
    
        public virtual Sal_LocationWiseSalesNCollectionTarget Sal_LocationWiseSalesNCollectionTarget { get; set; }
    }
}
