//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SalesAgreementPrePost_DataFromExternalSources
    {
        public string CustomerName { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<byte> AgreementType { get; set; }
        public string CustomerType { get; set; }
        public string PackageCode { get; set; }
        public string ModeOfPaymentID { get; set; }
        public string YearMonth { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public Nullable<byte> NumberOfInstallment { get; set; }
        public decimal PackagePrice { get; set; }
        public string DiscountID { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal AmountAfterDiscount { get; set; }
        public string DownPaymentID { get; set; }
        public byte STDDownPaymentPercentage { get; set; }
        public decimal DownPaymentAmount { get; set; }
        public decimal TotalPrincipalReceivable { get; set; }
        public string ServiceChargeID { get; set; }
        public byte STDServiceChargePercentage { get; set; }
        public decimal TotalServiceChargeReceivable { get; set; }
        public decimal TotalPrincipalPlusServiceChargeReceivable { get; set; }
        public decimal InstallmentSize { get; set; }
        public decimal InstallmentSizePrincipal { get; set; }
        public decimal InstallmentSizeServiceCharge { get; set; }
        public Nullable<byte> ScheduledCollectionDay { get; set; }
        public string UnitCode { get; set; }
        public string ProjectCode { get; set; }
        public string ProgramCode { get; set; }
        public string CashMemoNo { get; set; }
        public string CashMemoUsesID { get; set; }
        public string RefMemoNo { get; set; }
        public string SourceOrUserName { get; set; }
        public string RefDeviceUserEmployeeID { get; set; }
        public string RefExternalDeviceID { get; set; }
        public string RefExternalTransactionNo { get; set; }
        public decimal TechnicalFees { get; set; }
        public decimal Subsidies { get; set; }
        public byte DisbursementNo { get; set; }
        public string SalespersonCode { get; set; }
        public bool IsReSales { get; set; }
        public string PanelItemCode { get; set; }
        public string PanelSerialNo { get; set; }
        public string BatteryItemCode { get; set; }
        public string BatterySerialNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsTransferredToFinalTable { get; set; }
    
        public virtual Common_UnitInfo Common_UnitInfo { get; set; }
        public virtual Inv_ItemNItemCategoryWithSerialNoMaster Inv_ItemNItemCategoryWithSerialNoMaster { get; set; }
        public virtual Inv_ItemNItemCategoryWithSerialNoMaster Inv_ItemNItemCategoryWithSerialNoMaster1 { get; set; }
        public virtual Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage Sal_Validation_CustomerTypeVsModeOfPaymentVsPackage { get; set; }
        public virtual Sal_Validation_ModeOfPaymentNPackageVsDiscount Sal_Validation_ModeOfPaymentNPackageVsDiscount { get; set; }
        public virtual Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy { get; set; }
        public virtual Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy Sal_Validation_ProgramVsCustomerTypeNModeOfPaymentWiseServiceChargePolicy { get; set; }
    }
}
