//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Light
    {
        public Sal_Light()
        {
            this.Sal_Validation_CapacityVsLight = new HashSet<Sal_Validation_CapacityVsLight>();
        }
    
        public string LightID { get; set; }
        public string Description { get; set; }
        public byte Status { get; set; }
        public byte LightQuantity { get; set; }
    
        public virtual ICollection<Sal_Validation_CapacityVsLight> Sal_Validation_CapacityVsLight { get; set; }
    }
}
