//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_ItemSetDetail
    {
        public string ItemSetCode { get; set; }
        public byte CompSeqNo { get; set; }
        public string ItemCategory { get; set; }
        public string ItemCapacity { get; set; }
        public string ItemModel { get; set; }
        public Nullable<double> FixedQuantity { get; set; }
        public bool IsItAMandatoryItem { get; set; }
        public bool IsSerialNoMandatory { get; set; }
        public byte Status { get; set; }
    
        public virtual Sal_ItemSetMaster Sal_ItemSetMaster { get; set; }
    }
}
