//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SparePartsSales_DataFromExternalSources
    {
        public string ItemDescription { get; set; }
        public double ItemQuantity { get; set; }
        public string LocationCode { get; set; }
        public Nullable<System.DateTime> SPSDate { get; set; }
        public string YearMonth { get; set; }
        public string ProjectCode { get; set; }
        public string ProgramCode { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal SalesAmountAfterDiscount { get; set; }
        public string CashMemoNo { get; set; }
        public string CashMemoUsesID { get; set; }
        public string SourceOrUserName { get; set; }
        public string RefExternalDeviceID { get; set; }
        public string RefExternalTransactionNo { get; set; }
        public string SalespersonCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> IsTransferredToFinalTable { get; set; }
        public string RefDeviceUserEmployeeID { get; set; }
    
        public virtual Common_LocationInfo Common_LocationInfo { get; set; }
    }
}
