//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SalesAgreementClosedWithFullPaidOrWaive
    {
        public string CustomerCode { get; set; }
        public System.DateTime TransDate { get; set; }
        public System.DateTime AgreementClosedDate { get; set; }
        public byte MonthUsage { get; set; }
        public Nullable<decimal> TotalPrincipalReceivableAsPerAgreement { get; set; }
        public Nullable<decimal> TotalServiceChargeReceivableAsPerAgreement { get; set; }
        public Nullable<byte> DueNoOfInstllmentAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> TotalServiceChargeReceivableConsideringDueNoOfInstallmentAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> TotalServiceChargeRecoveredAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> TotalPrincipalWithoutDPRecoveredAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> TotalAdvanceReceivedAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> TotalPrincipalWithoutDPPlusServiceChargePlusAdvanceReceivedAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> RemainingPrincipalReceivableAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> RemainingServiceChargeReceivableAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> RemainingServiceChargeReceivableConsideringDueNoOfInstallmentAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> AE_PrincipalReceivableWaived { get; set; }
        public Nullable<decimal> ServiceChargeReceivableConsideringNotYetDueNoOfInstallment { get; set; }
        public Nullable<decimal> AE_ServiceChargeReceivableConsideringDueNoOfInstallmentWaived { get; set; }
        public Nullable<decimal> AE_AdvanceBalanceTransferredToCompanyGain { get; set; }
        public Nullable<decimal> OverdueBalanceAtTheEndOfClosedMonth { get; set; }
        public Nullable<decimal> OutstandingBalanceAtTheEndOfClosedMonth { get; set; }
        public bool IsClosedWithWaive { get; set; }
        public string ApprovalNo { get; set; }
        public string Remarks { get; set; }
        public string RefAEUnitCode { get; set; }
        public Nullable<System.DateTime> RefAETransDate { get; set; }
        public string RefAEProjectCode { get; set; }
        public string RefAETransNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
