//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_CustomerTrainingTransDetails
    {
        public string UnitCode { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public string CustomerCode { get; set; }
        public System.DateTime CustomerTrainingDate { get; set; }
        public byte TrainingBatchNo { get; set; }
    
        public virtual Sal_CustomerTrainingTransMaster Sal_CustomerTrainingTransMaster { get; set; }
        public virtual Sal_CustomerStatus Sal_CustomerStatus { get; set; }
    }
}
