//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_ListedUnitPriceForSparePartsSales
    {
        public string YearMonth { get; set; }
        public string ItemCode { get; set; }
        public byte StoreLocation { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
