//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Validation_ModeOfPaymentWiseDiscountPolicy
    {
        public Sal_Validation_ModeOfPaymentWiseDiscountPolicy()
        {
            this.Sal_Validation_ModeOfPaymentNPackageVsDiscount = new HashSet<Sal_Validation_ModeOfPaymentNPackageVsDiscount>();
        }
    
        public string ModeOfPaymentID { get; set; }
        public string DiscountID { get; set; }
        public string Description { get; set; }
        public byte DiscountPercentage { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public byte Status { get; set; }
        public bool IsDiscountAFixedAmount { get; set; }
        public decimal DiscountFixedAmount { get; set; }
    
        public virtual Sal_ModeOfPayment Sal_ModeOfPayment { get; set; }
        public virtual ICollection<Sal_Validation_ModeOfPaymentNPackageVsDiscount> Sal_Validation_ModeOfPaymentNPackageVsDiscount { get; set; }
    }
}
