//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_ItemSetMaster
    {
        public Sal_ItemSetMaster()
        {
            this.Sal_ItemSetDetail = new HashSet<Sal_ItemSetDetail>();
            this.Sal_SparePartsSalesMaster = new HashSet<Sal_SparePartsSalesMaster>();
        }
    
        public string ItemSetCode { get; set; }
        public string Description { get; set; }
        public string Capacity { get; set; }
        public string Light { get; set; }
        public decimal PerUnitSalesPrice { get; set; }
        public bool IsPriceChangeable { get; set; }
        public Nullable<decimal> MinSalesPrice { get; set; }
        public Nullable<decimal> MaxSalesPrice { get; set; }
        public string FixedModeOfPayment { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Sal_ItemSetDetail> Sal_ItemSetDetail { get; set; }
        public virtual ICollection<Sal_SparePartsSalesMaster> Sal_SparePartsSalesMaster { get; set; }
    }
}
