//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_ODCustomerGrading
    {
        public string YearMonth { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<byte> NumberOfInstallment { get; set; }
        public Nullable<byte> NoOfMonthPassed { get; set; }
        public byte DueNoOfInstllment { get; set; }
        public decimal OverdueBalance { get; set; }
        public Nullable<decimal> InstallmentSize { get; set; }
        public double ApproximateNoOfODInstallmentBeforeRound { get; set; }
        public byte ApproximateNoOfODInstallmentRounded { get; set; }
        public byte ApproximateNoOfInstallmentPaid { get; set; }
        public decimal OutstandingBalance { get; set; }
        public string ODGradeThisMonth { get; set; }
        public string EmployeeAsFPR { get; set; }
        public string CustomerUnit { get; set; }
        public Nullable<System.DateTime> LastUMNextRecoveryDateIfRemainingODBalance { get; set; }
        public string LastUMRemarks { get; set; }
        public Nullable<System.DateTime> LastUMRemarksOn { get; set; }
    }
}
