//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_CustomerWiseOverdueBalanceForTracker
    {
        public string UnitCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> OverdueBalance { get; set; }
        public Nullable<decimal> RecoveredUptoLastWeek { get; set; }
        public Nullable<decimal> RecoWeek01 { get; set; }
        public Nullable<decimal> RecoWeek02 { get; set; }
        public Nullable<decimal> RecoWeek03 { get; set; }
        public Nullable<decimal> RecoWeek04 { get; set; }
        public Nullable<decimal> RecoWeek05 { get; set; }
        public Nullable<decimal> RecoWeek06 { get; set; }
        public Nullable<decimal> RecoWeek07 { get; set; }
        public Nullable<decimal> RecoWeek08 { get; set; }
        public Nullable<decimal> RecoWeek09 { get; set; }
        public Nullable<decimal> RecoWeek10 { get; set; }
        public Nullable<decimal> RecoWeek11 { get; set; }
        public Nullable<decimal> RecoWeek12 { get; set; }
        public Nullable<decimal> RecoWeek13 { get; set; }
        public Nullable<decimal> RecoWeek14 { get; set; }
        public Nullable<decimal> RecoWeek15 { get; set; }
        public Nullable<decimal> RecoWeek16 { get; set; }
        public Nullable<decimal> RecoWeek17 { get; set; }
        public Nullable<decimal> RecoWeek18 { get; set; }
        public Nullable<decimal> RecoWeek19 { get; set; }
        public Nullable<decimal> RecoWeek20 { get; set; }
        public Nullable<decimal> RecoWeek21 { get; set; }
        public Nullable<decimal> RecoWeek22 { get; set; }
        public Nullable<decimal> RecoWeek23 { get; set; }
        public Nullable<decimal> RecoWeek24 { get; set; }
        public Nullable<decimal> RecoWeek25 { get; set; }
        public Nullable<decimal> RecoWeek26 { get; set; }
        public Nullable<decimal> RecoWeek27 { get; set; }
        public Nullable<decimal> RecoWeek28 { get; set; }
        public Nullable<decimal> RecoWeek29 { get; set; }
        public Nullable<decimal> RecoWeek30 { get; set; }
        public Nullable<decimal> RecoWeek31 { get; set; }
        public Nullable<decimal> RecoWeek32 { get; set; }
        public Nullable<decimal> RecoWeek33 { get; set; }
        public Nullable<decimal> RecoWeek34 { get; set; }
        public Nullable<decimal> RecoWeek35 { get; set; }
        public Nullable<decimal> RecoWeek36 { get; set; }
        public Nullable<decimal> RecoWeek37 { get; set; }
        public Nullable<decimal> RecoWeek38 { get; set; }
        public Nullable<decimal> RecoWeek39 { get; set; }
        public Nullable<decimal> RecoWeek40 { get; set; }
        public Nullable<decimal> RecoWeek41 { get; set; }
        public Nullable<decimal> RecoWeek42 { get; set; }
        public Nullable<decimal> RecoWeek43 { get; set; }
        public Nullable<decimal> RecoWeek44 { get; set; }
        public Nullable<decimal> RecoWeek45 { get; set; }
        public Nullable<decimal> RecoWeek46 { get; set; }
        public Nullable<decimal> RecoWeek47 { get; set; }
        public Nullable<decimal> RecoWeek48 { get; set; }
        public Nullable<decimal> RecoWeek49 { get; set; }
        public Nullable<decimal> RecoWeek50 { get; set; }
        public Nullable<decimal> RecoWeek51 { get; set; }
        public Nullable<decimal> RecoWeek52 { get; set; }
    }
}
