//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_CustomerTrainingSchedule
    {
        public Sal_CustomerTrainingSchedule()
        {
            this.Sal_CustomerTrainingTransMaster = new HashSet<Sal_CustomerTrainingTransMaster>();
        }
    
        public string UnitCode { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public byte ScheduledBatchNo { get; set; }
        public byte NoOfParticipantScheduled { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte Status { get; set; }
    
        public virtual Common_UnitInfo Common_UnitInfo { get; set; }
        public virtual ICollection<Sal_CustomerTrainingTransMaster> Sal_CustomerTrainingTransMaster { get; set; }
    }
}
