//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_CustomerType
    {
        public Sal_CustomerType()
        {
            this.Sal_Validation_CustomerTypeVsModeOfPayment = new HashSet<Sal_Validation_CustomerTypeVsModeOfPayment>();
        }
    
        public string CustomerTypeID { get; set; }
        public string Description { get; set; }
        public byte SortingOrder { get; set; }
        public Nullable<byte> IDCOLCustomerTypeID { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Sal_Validation_CustomerTypeVsModeOfPayment> Sal_Validation_CustomerTypeVsModeOfPayment { get; set; }
    }
}
