//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Validation_UnitVsUpazilla
    {
        public string UnitCode { get; set; }
        public string UpazillaCode { get; set; }
        public byte Status { get; set; }
    
        public virtual Common_UpazillaInfo Common_UpazillaInfo { get; set; }
        public virtual Common_UnitInfo Common_UnitInfo { get; set; }
    }
}
