//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy
    {
        public Sal_Validation_ModeOfPaymentNPackageWiseDownpaymentPolicy()
        {
            this.Aud_AuditAdjustmentObservationOnSalesAgreement = new HashSet<Aud_AuditAdjustmentObservationOnSalesAgreement>();
            this.Sal_SalesAgreementPrePost = new HashSet<Sal_SalesAgreementPrePost>();
            this.Sal_SalesAgreement = new HashSet<Sal_SalesAgreement>();
            this.Sal_SalesAgreementPrePost_DataFromExternalSources = new HashSet<Sal_SalesAgreementPrePost_DataFromExternalSources>();
        }
    
        public string ModeOfPaymentID { get; set; }
        public string PackageCode { get; set; }
        public string DownPaymentID { get; set; }
        public string Description { get; set; }
        public byte DownPaymentPercentage { get; set; }
        public string DPPercentageMinFixMax { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public byte Status { get; set; }
        public bool IsDPAFixedAmount { get; set; }
        public decimal DownPaymentFixedAmount { get; set; }
    
        public virtual ICollection<Aud_AuditAdjustmentObservationOnSalesAgreement> Aud_AuditAdjustmentObservationOnSalesAgreement { get; set; }
        public virtual Sal_PackageMaster Sal_PackageMaster { get; set; }
        public virtual Sal_Validation_ModeOfPaymentVsPackage Sal_Validation_ModeOfPaymentVsPackage { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost> Sal_SalesAgreementPrePost { get; set; }
        public virtual ICollection<Sal_SalesAgreement> Sal_SalesAgreement { get; set; }
        public virtual ICollection<Sal_SalesAgreementPrePost_DataFromExternalSources> Sal_SalesAgreementPrePost_DataFromExternalSources { get; set; }
    }
}
