//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_CustomerInfoBackup
    {
        public string CustomerCode { get; set; }
        public System.DateTime BackupEntryTime { get; set; }
        public string OldCustomerName { get; set; }
        public string OldFathersOrHusbandName { get; set; }
        public string OldRelationWithGuardian { get; set; }
        public string OldMothersName { get; set; }
        public string OldNationalIDCard { get; set; }
        public string OldGender { get; set; }
        public string OldPhoneNo { get; set; }
        public Nullable<bool> OldIsMobileNoMandatory { get; set; }
        public string OldVillage { get; set; }
        public string OldPostOffice { get; set; }
        public string OldUnionID { get; set; }
        public string OldThanaID { get; set; }
        public string OldDistrictCode { get; set; }
        public string OldUnitCode { get; set; }
        public string OldCustomerType { get; set; }
        public string OldOccupation { get; set; }
        public string OldIncomeRange { get; set; }
        public Nullable<byte> OldTotalFamilyMember { get; set; }
        public Nullable<byte> OldWomenInTotalFamilyMember { get; set; }
        public Nullable<bool> OldIsConsultedWithWomenMemberForInstallationOfLamps { get; set; }
        public string OldFuelUsedBeforeSHS { get; set; }
        public Nullable<byte> OldFuelConsumptionPerMonth { get; set; }
        public string OldCreatedBy { get; set; }
        public System.DateTime OldCreatedOn { get; set; }
        public string OldModifiedBy { get; set; }
        public Nullable<System.DateTime> OldModifiedOn { get; set; }
        public byte OldStatus { get; set; }
        public string NewCustomerName { get; set; }
        public string NewVillage { get; set; }
        public string NewPostOffice { get; set; }
        public string NewUnionID { get; set; }
        public string NewThanaID { get; set; }
        public string NewDistrictCode { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Common_DistrictInfo Common_DistrictInfo { get; set; }
        public virtual Common_UnionInfo Common_UnionInfo { get; set; }
        public virtual Common_UnitInfo Common_UnitInfo { get; set; }
        public virtual Common_UpazillaInfo Common_UpazillaInfo { get; set; }
    }
}
