//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class SalesDataEntryStatus
    {
        public string Zone_Name { get; set; }
        public string Region_Name { get; set; }
        public string Unit_Code { get; set; }
        public string Unit_Name { get; set; }
        public int A_OpeningNoOfActiveCustomer { get; set; }
        public short B_NewCreditSalesThisMonth { get; set; }
        public short C_TransferInFromOtherUnitAndAccepted { get; set; }
        public short D_TransferInFromOtherUnitButNotAccepted { get; set; }
        public short E_FullPaidThisMonth { get; set; }
        public short F_SystemReturnThisMonth { get; set; }
        public short G_TransferOutToOtherUnitAndAccepted { get; set; }
        public short H_TransferOutToOtherUnitButNotAccepted { get; set; }
        public int I_ClosingNoOfActiveCustomer__G_A_B_C_D_E_F_G_H_ { get; set; }
        public short NoOfCashSalesThisMonth { get; set; }
        public decimal CashSalesAmountThisMonth { get; set; }
        public decimal DPCollectionThisMonth { get; set; }
        public decimal RegularOrODRecoveryThisMonth { get; set; }
        public decimal TotalOverdue { get; set; }
        public decimal TotalAdvance { get; set; }
        public decimal TotalOutstanding { get; set; }
        public Nullable<System.DateTime> FinalizedByRM { get; set; }
        public Nullable<System.DateTime> FinalizedByZM { get; set; }
        public Nullable<System.DateTime> FinalizedByHO { get; set; }
    }
}
