//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class SalSalesNCollectionTargetVsAchievementForGraph
    {
        public Nullable<int> Day { get; set; }
        public int TargetForSales { get; set; }
        public int AchievementForSales { get; set; }
        public decimal TargetForRegularCollection { get; set; }
        public decimal AchievementForRegularCollection { get; set; }
        public decimal TargetForODCollection { get; set; }
        public decimal AchievementForODCollection { get; set; }
    }
}
