//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHSDistributionPlan_IndividualItem
    {
        public string DistribScheduleNo { get; set; }
        public string RouteNo { get; set; }
        public string LocationCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> ItemQuantity { get; set; }
    
        public virtual SHSDistributionPlan_RootWiseLocation SHSDistributionPlan_RootWiseLocation { get; set; }
    }
}
