//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHSDistributionPlan_Master
    {
        public SHSDistributionPlan_Master()
        {
            this.SHSDistributionPlan_RootWiseLocation = new HashSet<SHSDistributionPlan_RootWiseLocation>();
        }
    
        public string DistribScheduleNo { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public string ScheduleNotes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string RefScheduleNo { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual ICollection<SHSDistributionPlan_RootWiseLocation> SHSDistributionPlan_RootWiseLocation { get; set; }
    }
}
