//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHSDistributionPlan_RootWiseLocation
    {
        public SHSDistributionPlan_RootWiseLocation()
        {
            this.Inv_VendorChallanWithItemReferenceToCheck = new HashSet<Inv_VendorChallanWithItemReferenceToCheck>();
            this.SHSDistributionPlan_IndividualItem = new HashSet<SHSDistributionPlan_IndividualItem>();
            this.SHSDistributionPlan_RootWiseLocationNPackage = new HashSet<SHSDistributionPlan_RootWiseLocationNPackage>();
        }
    
        public string DistribScheduleNo { get; set; }
        public string RouteNo { get; set; }
        public string LocationCode { get; set; }
        public string VendorChallanNoForPackage { get; set; }
        public string VendorChallanNoForSpareParts { get; set; }
    
        public virtual ICollection<Inv_VendorChallanWithItemReferenceToCheck> Inv_VendorChallanWithItemReferenceToCheck { get; set; }
        public virtual ICollection<SHSDistributionPlan_IndividualItem> SHSDistributionPlan_IndividualItem { get; set; }
        public virtual SHSDistributionPlan_Master SHSDistributionPlan_Master { get; set; }
        public virtual ICollection<SHSDistributionPlan_RootWiseLocationNPackage> SHSDistributionPlan_RootWiseLocationNPackage { get; set; }
    }
}
