//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class SparePartSetDetils
    {
        public string ItemSetCode { get; set; }
        public string ItemCategoryID { get; set; }
        public string ItemCategory { get; set; }
        public string ItemCapacityID { get; set; }
        public string ItemCapacity { get; set; }
        public string ItemModelID { get; set; }
        public string ItemModel { get; set; }
        public Nullable<double> FixedQuantity { get; set; }
        public Nullable<bool> IsItemCapacityAvailable { get; set; }
        public Nullable<bool> IsItemModelAvailable { get; set; }
    }
}
