//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class SummarySheetForRegionalSalesPosting
    {
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> TotalSales { get; set; }
        public Nullable<int> ReSales { get; set; }
        public Nullable<int> CashSales { get; set; }
        public Nullable<int> CreditSales { get; set; }
        public Nullable<double> TotalPackagePrice { get; set; }
        public Nullable<double> TotalActualPayable { get; set; }
        public Nullable<double> TotalDP { get; set; }
        public Nullable<double> TotalServiceCharge { get; set; }
        public Nullable<double> TotalLoanAmount { get; set; }
    }
}
