//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class SummarySheetForRegionalSalesPostingDetails
    {
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string FatherName { get; set; }
        public string Village { get; set; }
        public string PostOffice { get; set; }
        public string UpazillaName { get; set; }
        public string DistrictName { get; set; }
        public string PackageName { get; set; }
        public Nullable<double> PackagePrice { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<double> ActualPayable { get; set; }
        public Nullable<double> DPAmount { get; set; }
        public Nullable<double> ServiceChargeAmount { get; set; }
        public string CustomerType { get; set; }
        public Nullable<double> InstallmentAmount { get; set; }
        public string RegularOrResale { get; set; }
        public string PanelSerialNo { get; set; }
        public string BatterySerialNo { get; set; }
        public string PanelSerial { get; set; }
        public string BatterySerial { get; set; }
    }
}
