//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class SummaryForTheDayClosingForAccountingInfo
    {
        public Nullable<decimal> CashInHandOpeningBalance { get; set; }
        public Nullable<decimal> CashInHandInFlow { get; set; }
        public Nullable<decimal> CashInHandOutFlow { get; set; }
        public Nullable<decimal> CashInHandClosingBalance { get; set; }
        public Nullable<decimal> CashAtBankOpeningBalance { get; set; }
        public Nullable<decimal> CashAtBankInFlow { get; set; }
        public Nullable<decimal> CashAtBankOutFlow { get; set; }
        public Nullable<decimal> CashAtBankClosingBalance { get; set; }
        public Nullable<decimal> CollectionReconciliationBalance { get; set; }
    }
}
