//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class SummaryForTheDayClosingForCollectionInfo
    {
        public Nullable<decimal> CurrentCollectionAchievementThisMonthUptoToday { get; set; }
        public decimal CurrentCollectionTargetThisMonth { get; set; }
        public Nullable<decimal> OverdueCollectionAchievementThisMonthUptoToday { get; set; }
        public decimal OverdueCollectionTargetThisMonth { get; set; }
    }
}
