//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class SummaryForTheDayClosingForInventoryInfo
    {
        public string ItemCategory { get; set; }
        public double OpeningBalance { get; set; }
        public double ReceivedUptoYesterday { get; set; }
        public double ReceivedToday { get; set; }
        public double IssuedUptoYesterday { get; set; }
        public double IssuedToday { get; set; }
        public double ClosingBalance { get; set; }
    }
}
