//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class SystemReturnOrFullPaidCustomers
    {
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime AgreementDate { get; set; }
        public Nullable<int> NoOfMonthAtCustomerEnd { get; set; }
        public string Package { get; set; }
        public Nullable<decimal> OverdueOrAdvanceBalance { get; set; }
        public Nullable<decimal> OutstandingBalance { get; set; }
        public string ReasonForSystemReturn { get; set; }
    }
}
