//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RASolarERP.Model
{
    using System;
    
    public partial class WeeklySalesNCollectionStatus
    {
        public string Zone_Name { get; set; }
        public string Region_Name { get; set; }
        public string Unit_Code { get; set; }
        public string Unit_Name { get; set; }
        public decimal WeeklyTarget { get; set; }
        public decimal WeeklyAchievement { get; set; }
        public Nullable<decimal> WeeklyVarianceInAmount { get; set; }
        public Nullable<decimal> WeeklyVarianceInPercentage { get; set; }
        public decimal CumulativeTarget { get; set; }
        public decimal CumulativeAchievement { get; set; }
        public Nullable<decimal> CumVarianceInAmount { get; set; }
        public Nullable<decimal> CumVarianceInPercentage { get; set; }
        public string Remarks { get; set; }
    }
}
